pingidentity/terraform-provider-pingone

- .changelog/57.txt
- internal/service/base/resource_environment.go
To prevent environments being created with all products enabled (where API changes may conflict with the SDK), products (the bill of materials) is set at the same time as environment creation
> set products on environment creation

- .changelog/311.txt
- docs/resources/application.md
- internal/service/sso/resource_application.go
- internal/service/sso/resource_application_test.go
Testing evidence (EU region):
```
TF_LOG= TF_LOG_PATH= TF_ACC=1 go test -v -timeout 240s -run ^TestAccApplication_NativeKerberos github.com/pingidentity/terraform-provider-pingone/internal/service/sso
=== RUN   TestAccApplication_NativeKerberos
=== PAUSE TestAccApplication_NativeKerberos
=== CONT  TestAccApplication_NativeKerberos
--- PASS: TestAccApplication_NativeKerberos (35.58s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/sso 35.993s
```
> `pingone_application`: Provide support for certificate based authentication.

- .changelog/372.txt
- docs/resources/mfa_application_push_credential.md
- docs/resources/mfa_policy.md
- examples/resources/pingone_mfa_application_push_credential/resource.tf
- examples/resources/pingone_mfa_policy/resource-mobile-authenticator.tf
Documentation: Remove deprecated attributes from example HCL
- `resource/pingone_mfa_application_push_credential` 
- `resource/pingone_mfa_policy`
> Remove deprecated attributes from examples

- docs/resources/credential_type.md
- internal/service/credentials/resource_credential_type.go
- internal/service/credentials/resource_credential_type_test.go
Clarified the `title` and `description` fields in the credential type align to the ${cardTitle} and ${cardSubtitle} fields in the card_design_template.  Previously, the documentation incorrectly stated the `metadata.name` and `metadata.description` fields aligned to those card values.
Corrected the validation rules and test cases to align to the above also.
All tests within the test suite passed.  Focus on the credential type tests also passed.
--- PASS: TestAccCredentialType_MetaData (0.64s)
=== CONT  TestAccCredentialTypeDataSource_NotFound
--- PASS: TestAccCredentialTypeDataSource_NotFound (0.73s)
=== CONT  TestAccCredentialTypeDataSource_ByIDFull
--- PASS: TestAccCredentialTypesDataSource_NotFound (6.80s)
```shell
TF_LOG=WARN TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout …
```
> Improvements to credential type documentation and validation bug fix.

- internal/service/base/data_source_agreement_test.go
- internal/service/base/resource_agreement_localization_revision_test.go
- internal/service/risk/resource_risk_predictor_test.go
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccAgreement github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccAgreementLocalizationDataSource_ByNameFull
=== PAUSE TestAccAgreementLocalizationDataSource_ByNameFull
=== RUN   TestAccAgreementLocalizationDataSource_ByLocaleFull
=== PAUSE TestAccAgreementLocalizationDataSource_ByLocaleFull
=== RUN   TestAccAgreementLocalizationDataSource_ByIDFull
=== PAUSE TestAccAgreementLocalizationDataSource_ByIDFull
=== RUN   TestAccAgreementLocalizationDataSource_NotFound
=== PAUSE TestAccAgreementLocalizationDataSource_NotFound
=== RUN   TestAccAgreementDataSource_ByNameFull
=== PAUSE TestAccAgreementDataSource_ByNameFull
=== RUN …
```
> Corrected date-based tests

- .changelog/406.txt
- docs/data-sources/credential_type.md
- docs/resources/credential_issuance_rule.md
- docs/resources/digital_wallet_application.md
- internal/service/credentials/data_source_credential_issuer_profile.go
- internal/service/credentials/data_source_credential_type.go
- internal/service/credentials/resource_credential_issuance_rule.go
- internal/service/credentials/resource_credential_issuance_rule_test.go
- internal/service/credentials/resource_credential_issuer_profile.go
- internal/service/credentials/resource_digital_wallet_application.go
```release-note:note
`data_source/pingone_credential_type`: Corrected typo in data source description.
```
```release-note:bug
`resource/pingone_digital_wallet_application`: Fixed incorrect replacement of resource if `application_id` value was changed.
`resource/pingone_credential_issuance_rule`: Fixed incorrect replacement of resource if `digital_wallet_id` value was changed.
`resource/pingone_credential_issuer_profile`: Fixed mismatched `created_at` and `updated_at` mapping.
`data_source/pingone_credential_issuer_profile`: Fixed mismatched `created_at` and `updated_at` mapping.
```
`credential_issuance_rule` is no longer replaced if the `digital_wallet_application_id` is changed:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are …
```
> Schema corrections for Issue 405 and documentation updates

- .changelog/412.txt
- docs/resources/sign_on_policy_action.md
- internal/service/sso/resource_sign_on_policy_action.go
- internal/service/sso/resource_sign_on_policy_action_test.go
- internal/service/sso/schema_sign_on_policy_action.go
- templates/resources/sign_on_policy_action.md.tmpl
* `resource/pingone_sign_on_policy_action`: Fix plugin panic crash when defining `conditions.user_attribute_equals` in a priority 1 MFA sign-on policy.
* `resource/pingone_sign_on_policy_action`: Adjust documentation to clarify the use of the `conditions.user_attribute_equals` condition in MFA policy actions.
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccSignOnPolicyAction_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccSignOnPolicyAction_LoginAction
=== PAUSE TestAccSignOnPolicyAction_LoginAction
=== RUN   TestAccSignOnPolicyAction_IDFirstAction
=== PAUSE TestAccSignOnPolicyAction_IDFirstAction
=== RUN   TestAccSignOnPolicyAction_MFAAction
=== PAUSE TestAccSignOnPolicyAction_MFAAction …
```
> `resource/pingone_sign_on_policy_action`: Fix plugin panic crash when defining `conditions.user_attribute_equals` in a priority 1 `mfa` sign-on policy

- internal/service/risk/resource_risk_policy.go
* Correct Risk Policy import error message
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccRiskPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/risk
```
```shell
=== RUN   TestAccRiskPolicy_NewEnv
=== PAUSE TestAccRiskPolicy_NewEnv
=== RUN   TestAccRiskPolicy_Full
=== PAUSE TestAccRiskPolicy_Full
=== RUN   TestAccRiskPolicy_Scores
=== PAUSE TestAccRiskPolicy_Scores
=== RUN   TestAccRiskPolicy_Weights
=== PAUSE TestAccRiskPolicy_Weights
=== RUN   TestAccRiskPolicy_ChangeType
=== PAUSE TestAccRiskPolicy_ChangeType
=== RUN   TestAccRiskPolicy_PolicyOverrides
=== PAUSE TestAccRiskPolicy_PolicyOverrides
=== CONT  TestAccRiskPolicy_NewEnv
=== CONT  TestAccRiskPolicy_Weights
=== CONT  TestAccRiskPolicy_Scores
=== CONT …
```
> Correct Risk Policy import error message

- .changelog/417.txt
- internal/service/base/data_source_environment.go
- internal/service/base/resource_agreement_localization_revision.go
- internal/service/base/resource_environment.go
- internal/service/credentials/data_source_credential_issuance_rule.go
- internal/service/credentials/data_source_credential_type.go
- internal/service/credentials/resource_credential_issuance_rule.go
- internal/service/credentials/resource_credential_type.go
* `data-source/pingone_environment`: Code optimisation of ENUM values to TF state.
* `resource/pingone_agreement_localization_revision`: Code optimisation of ENUM values to TF state.
* `resource/pingone_environment`: Code optimisation of ENUM values to TF state.
* `data-source/pingone_credential_issuance_rule`: Code optimisation of ENUM values to TF state.
* `data-source/pingone_credential_type`: Code optimisation of ENUM values to TF state.
* `resource/pingone_credential_issuance_rule`: Code optimisation of ENUM values to TF state.
* `resource/pingone_credential_type`: Code optimisation of ENUM values to TF state.
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccEnvironmentDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/s …
```
> Optimise code for conversion of ENUM to TF state

- .changelog/428.txt
- docs/resources/notification_template_content.md
- internal/service/base/resource_notification_template_content.go
- internal/service/base/resource_notification_template_content_test.go
Support P1Verify and P1Credentials notification templates: `email_phone_verification`, `id_verification`, `credential_issued`, `credential_updated`, `digital_wallet_pairing`, `credential_revoked`.
For consistency, I stayed with the existing testing structure and did not introduce new tests specific to the P1Verify and P1Credentials notification templates, which are similar to other P1 notification templates.
However performed one-off tests to ensure templates were functional.  However, executed regression tests to ensure the general notification template testing remained successful.
```shell
for i in `cat internal/service/base/resource_notification_template_content_test.go | grep TestAccNotificationTemplateContent_ | cut -d'(' -f1 | cut -d' ' -f2`
do
echo "Running test: $i"
TF_LOG=INFO …
```
> Support p1verify and p1credentials notification templates.

- internal/service/base/resource_gateway_test.go
- internal/service/sso/resource_sign_on_policy_action_test.go
* Tests incorrectly using ports ending `636` without TLS enabled.  Corrected to non-TLS port values
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccSignOnPolicyAction_LoginAction_Gateway github.com/pingidentity/terraform-provider-pingone/internal/service/sso && TF_ACC=1 go test -v -timeout 240s -run ^TestAccGateway_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccSignOnPolicyAction_LoginAction_Gateway
=== PAUSE TestAccSignOnPolicyAction_LoginAction_Gateway
=== CONT  TestAccSignOnPolicyAction_LoginAction_Gateway
--- PASS: TestAccSignOnPolicyAction_LoginAction_Gateway (21.33s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/sso 21.917s
=== RUN   TestAccGateway_NewEnv
=== PAUSE …
```
> Correct gateway non-TLS tests

- .changelog/440.txt
- docs/resources/branding_settings.md
- docs/resources/branding_theme.md
- internal/service/base/resource_branding_settings.go
- internal/service/base/resource_branding_theme.go
* `resource/pingone_branding_theme`: Added missing schema validators to prevent misconfiguration of the single-object `background_image` and `logo` blocks.
* `resource/pingone_branding_settings`: Added missing schema validators to prevent misconfiguration of the single-object `logo_image` block.
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccBranding github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccBrandingSettings_Full
=== PAUSE TestAccBrandingSettings_Full
=== RUN   TestAccBrandingSettings_Minimal1
=== PAUSE TestAccBrandingSettings_Minimal1
=== RUN   TestAccBrandingSettings_Minimal2
=== PAUSE TestAccBrandingSettings_Minimal2
=== RUN   TestAccBrandingSettings_Minimal3
=== PAUSE …
```
> Add validators to list blocks to prevent multiple single-object configurations

- .changelog/452.txt
- docs/resources/risk_policy.md
- docs/resources/risk_predictor.md
- templates/resources/risk_policy.md.tmpl
- templates/resources/risk_predictor.md.tmpl
- Changed "Risk" documentation subcategory to "Protect", for the release of PingOne Protect.
> Changed "Risk" documentation subcategory to "Protect", for the release of PingOne Protect

- .changelog/457.txt
- docs/resources/application_resource_grant.md
- internal/service/sso/resource_application_resource_grant.go
- internal/service/sso/resource_application_resource_grant_test.go
* `pingone_application_resource_grant`: Add validation to disallow assignment of the `openid` scope from the `openid` resource to avoid error.
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccApplicationResourceGrant_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccApplicationResourceGrant_Change
=== PAUSE TestAccApplicationResourceGrant_Change
=== CONT  TestAccApplicationResourceGrant_OpenIDResource
=== CONT  TestAccApplicationResourceGrant_Change
=== CONT  TestAccApplicationResourceGrant_CustomResource …
```
> `pingone_application_resource_grant`: Add validation to disallow assignment of the `openid` scope from the `openid` resource to avoid error.

- .changelog/458.txt
- docs/resources/notification_policy.md
- internal/service/base/resource_notification_policy.go
- internal/service/base/resource_notification_policy_test.go
* `resource/pingone_notification_policy`: Now supports country limit configuration.
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccNotificationPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccNotificationPolicy_NewEnv
=== PAUSE TestAccNotificationPolicy_NewEnv
=== RUN   TestAccNotificationPolicy_Full
=== PAUSE TestAccNotificationPolicy_Full
=== RUN   TestAccNotificationPolicy_Quotas
=== PAUSE TestAccNotificationPolicy_Quotas
=== RUN   TestAccNotificationPolicy_CountryLimit
=== PAUSE TestAccNotificationPolicy_CountryLimit
=== CONT  TestAccNotificationPolicy_NewEnv
=== CONT  TestAccNotificationPolicy_Quotas
=== CONT  TestAccNotificationPolicy_Full
=== CONT  TestAccNotificationPolicy_CountryLimit
--- PASS: …
```
> Support country limit on `pingone_notification_policy` resource

- .changelog/469.txt
- internal/service/base/data_source_environment.go
* `data-source/pingone_environment`: Optimised environment filtering by name.
```shell
TF_ACC=1 go test -v -timeout 360s -run ^TestAccEnvironmentDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccEnvironmentDataSource_ByNameFull
=== PAUSE TestAccEnvironmentDataSource_ByNameFull
=== RUN   TestAccEnvironmentDataSource_ByNameMinimal
=== PAUSE TestAccEnvironmentDataSource_ByNameMinimal
=== RUN   TestAccEnvironmentDataSource_ByIDFull
=== PAUSE TestAccEnvironmentDataSource_ByIDFull
=== RUN   TestAccEnvironmentDataSource_ByIDMinimal
=== PAUSE TestAccEnvironmentDataSource_ByIDMinimal
=== RUN   TestAccEnvironmentDataSource_NotFound
=== PAUSE TestAccEnvironmentDataSource_NotFound
=== CONT  TestAccEnvironmentDataSource_ByNameFull
=== …
```
> Optimise environment data source filtering by name

- .changelog/472.txt
- internal/service/sso/resource_application.go
- internal/service/sso/resource_application_test.go
- internal/service/sso/resource_identity_provider.go
- internal/service/sso/resource_identity_provider_test.go
`resource/pingone_application`: Resolved error condition if optional `slo_window` value in the `saml_options` block was undefined.
`resource/pingone_identity_provider`: Resolved error condition if optional `slo_window` value in the `saml` block was undefined.
NOTE: All germane application tests were successful. The failed tests re: google signing-key and missing workforce environment are unrelated to the SAML `slo_window` changes and only relevant to missing, unrelated test environment configurations.
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccIdentityProvider_  github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run …
```
> Fix defect which triggers an error if optional SAML slo_window value is undefined.

- .changelog/470.txt
- docs/resources/webhook.md
- internal/service/base/resource_webhook.go
- internal/service/base/resource_webhook_test.go
`resource/pingone_webhook`: Now supports ip address exposed and useragent exposed in filter option configuration.
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 360s -run ^TestAccWebhook_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccWebhook_NewEnv
=== PAUSE TestAccWebhook_NewEnv
=== RUN   TestAccWebhook_Full
=== PAUSE TestAccWebhook_Full
=== RUN   TestAccWebhook_Minimal
=== PAUSE TestAccWebhook_Minimal
=== RUN   TestAccWebhook_Change
=== PAUSE TestAccWebhook_Change
=== RUN   TestAccWebhook_Applications
=== PAUSE TestAccWebhook_Applications
=== RUN   TestAccWebhook_Populations
=== PAUSE TestAccWebhook_Populations
=== CONT  TestAccWebhook_NewEnv
=== CONT  TestAccWebhook_Applications
=== CONT …
```
> Support `ip_address_exposed` and `useragent_exposed` in `filter_options` in `pingone_webhook.`

- .changelog/475.txt
- internal/service/sso/resource_application.go
* Fixed unable to update PKCE enforcement on OIDC worker app
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 360s -run ^TestAccApplication_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccApplication_NewEnv
=== PAUSE TestAccApplication_NewEnv
=== RUN   TestAccApplication_OIDCFullWeb
=== PAUSE TestAccApplication_OIDCFullWeb
=== RUN   TestAccApplication_OIDCMinimalWeb
=== PAUSE TestAccApplication_OIDCMinimalWeb
=== RUN   TestAccApplication_OIDCWebUpdate
=== PAUSE TestAccApplication_OIDCWebUpdate
=== RUN   TestAccApplication_OIDCFullNative
=== PAUSE TestAccApplication_OIDCFullNative
=== RUN   TestAccApplication_OIDCMinimalNative
=== PAUSE TestAccApplication_OIDCMinimalNative
=== RUN …
```
> Fixed unable to update PKCE enforcement on OIDC worker app

- .changelog/490.txt
- docs/resources/credential_issuance_rule.md
- internal/service/credentials/resource_credential_issuance_rule.go
- internal/service/credentials/resource_credential_issuance_rule_test.go
`resource/pingone_credential_issuance_rule`: Corrected `digital_wallet_application_id` from `REQUIRED` to `OPTIONAL` per API specification.
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccCredentialIssuanceRule_ github.com/pingidentity/terraform-provider-pingone/internal/service/credentials
```
```shell
=== RUN   TestAccCredentialIssuanceRule_Full
=== PAUSE TestAccCredentialIssuanceRule_Full
=== RUN   TestAccCredentialIssuanceRule_InvalidConfigs
=== PAUSE TestAccCredentialIssuanceRule_InvalidConfigs
=== CONT  TestAccCredentialIssuanceRule_Full
=== CONT  TestAccCredentialIssuanceRule_InvalidConfigs
--- PASS: TestAccCredentialIssuanceRule_InvalidConfigs (1.00s)
--- PASS: TestAccCredentialIssuanceRule_Full (60.64s)
PASS
ok …
```
> Correct `digital_wallet_application_id` validation from `REQUIRED` to `OPTIONAL`.

- .changelog/525.txt
- internal/service/sso/resource_sign_on_policy_action.go
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 600s -run ^TestAccSignOnPolicyAction_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccSignOnPolicyAction_RemovalDrift
=== PAUSE TestAccSignOnPolicyAction_RemovalDrift
=== RUN   TestAccSignOnPolicyAction_LoginAction
=== PAUSE TestAccSignOnPolicyAction_LoginAction
=== RUN   TestAccSignOnPolicyAction_LoginAction_Gateway
=== PAUSE TestAccSignOnPolicyAction_LoginAction_Gateway
=== RUN   TestAccSignOnPolicyAction_IDFirstAction
=== PAUSE TestAccSignOnPolicyAction_IDFirstAction
=== RUN   TestAccSignOnPolicyAction_MFAAction
=== PAUSE TestAccSignOnPolicyAction_MFAAction
=== RUN   TestAccSignOnPolicyAction_IDPAction
=== PAUSE TestAccSignOnPolicyAction_IDPAction
=== RUN …
```
> `resource/pingone_sign_on_policy_action`: Fix potential slice out of bounds issues

- .changelog/535.txt
- internal/service/base/resource_environment.go
* `resource/pingone_environment`: Fixed "Incompatible environment region for the organization tenant" error when the `region` parameter is defaulted from the client connection.
```shell
TF_ACC=1 go test -v -timeout 2400s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== PAUSE TestAccEnvironment_DeleteProductionEnvironmentProtection
=== RUN …
```
> Fixed "Incompatible environment region for the organization tenant" error when the `region` parameter is defaulted from the client connection

- .changelog/542.txt
- docs/resources/application.md
- internal/service/sso/resource_application.go
- internal/service/sso/resource_application_test.go
- `resource/pingone_application`: Added support for whether `requestedAuthnContext` is taken into account in SAML application policy decision-making.
```shell
TF_ACC=1 go test -v -timeout 2400s -run ^TestAccApplication_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccApplication_RemovalDrift
=== PAUSE TestAccApplication_RemovalDrift
=== RUN   TestAccApplication_NewEnv
=== PAUSE TestAccApplication_NewEnv
=== RUN   TestAccApplication_OIDCFullWeb
=== PAUSE TestAccApplication_OIDCFullWeb
=== RUN   TestAccApplication_OIDCMinimalWeb
=== PAUSE TestAccApplication_OIDCMinimalWeb
=== RUN   TestAccApplication_OIDCWebUpdate
=== PAUSE TestAccApplication_OIDCWebUpdate
=== RUN   TestAccApplication_OIDCFullNative
=== PAUSE …
```
> `resource/pingone_application`: Added support for whether `requestedAuthnContext` is taken into account in SAML application policy decision-making

- .changelog/543.txt
- docs/resources/group.md
- docs/resources/group_nesting.md
- internal/provider/sdkv2/provider.go
- internal/service/sso/resource_group.go
- internal/service/sso/resource_group_nesting.go
- internal/service/sso/resource_group_nesting_test.go
- internal/service/sso/resource_group_test.go
- internal/service/sso/service.go
- `resource/pingone_group`: Migrated to plugin framework.
- `resource/pingone_group_nesting`: Migrated to plugin framework.
```shell
TF_ACC=1 go test -v -timeout 2400s -run ^TestAccGroupNesting_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso && \
TF_ACC=1 go test -v -timeout 2400s -run ^TestAccGroup_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccGroupNesting_RemovalDrift
=== PAUSE TestAccGroupNesting_RemovalDrift
=== RUN   TestAccGroupNesting_Full
=== PAUSE TestAccGroupNesting_Full
=== RUN   TestAccGroupNesting_BadParameters
=== PAUSE TestAccGroupNesting_BadParameters
=== CONT  TestAccGroupNesting_RemovalDrift
=== CONT  TestAccGroupNesting_BadParameters
=== CONT  TestAccGroupNesting_Full
--- PASS: …
```
> Migrate group resources to plugin framework

- .changelog/560.txt
- docs/resources/application.md
- internal/service/sso/resource_application.go
- internal/service/sso/resource_application_test.go
- `resource/pingone_application`: Supports for additional refresh token replay protection on OIDC applications.
```shell
TF_ACC=1 go test -v -timeout 2400s -run ^TestAccApplication_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccApplication_RemovalDrift
=== PAUSE TestAccApplication_RemovalDrift
=== RUN   TestAccApplication_NewEnv
=== PAUSE TestAccApplication_NewEnv
=== RUN   TestAccApplication_OIDCFullWeb
=== PAUSE TestAccApplication_OIDCFullWeb
=== RUN   TestAccApplication_OIDCMinimalWeb
=== PAUSE TestAccApplication_OIDCMinimalWeb
=== RUN   TestAccApplication_OIDCWebUpdate
=== PAUSE TestAccApplication_OIDCWebUpdate
=== RUN   TestAccApplication_OIDCFullNative
=== PAUSE TestAccApplication_OIDCFullNative
=== RUN …
```
> Support for additional refresh token replay protection on OIDC applications

- .changelog/573.txt
- internal/service/sso/resource_application_resource_grant.go
- internal/service/sso/resource_application_resource_grant_test.go
- `resource/pingone_application_resource_grant`: Fixed inability to apply application grants to the Self-Service and Portal system applications.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccApplicationResourceGrant_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccApplicationResourceGrant_RemovalDrift
=== PAUSE TestAccApplicationResourceGrant_RemovalDrift
=== RUN   TestAccApplicationResourceGrant_SystemApplication
=== PAUSE TestAccApplicationResourceGrant_SystemApplication
=== RUN …
```
> Fix inability to apply application grants to the Self-Service and Portal system applications

- .changelog/574.txt
- internal/service/base/resource_environment.go
- internal/service/base/resource_system_application.go
- internal/service/sso/data_source_population.go
- `resource/pingone_environment`: Corrected deprecated retry method.
- `resource/pingone_system_application`: Corrected deprecated retry method.
- `data-source/pingone_population`: Corrected deprecated retry method.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccSystemApplication_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccPopulationDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== PAUSE …
```
> Corrected deprecated retry method

- .changelog/579.txt
- docs/data-sources/credential_type.md
- docs/resources/credential_type.md
- examples/resources/pingone_credential_type/resource.tf
- internal/service/credentials/data_source_credential_type.go
- internal/service/credentials/data_source_credential_type_test.go
- internal/service/credentials/resource_credential_type.go
- internal/service/credentials/resource_credential_type_test.go
`resource/pingone_credential_type`: 
- Added support for image attributes in a verifiable credential configuration.
- Improved test cases and migrated to dynamically-created test environments.
`data_source/pingone_credential_type`: 
- Added support for image attributes in a verifiable credential configuration.
- Improved test cases and migrated to dynamically-created test environments.
Reference:  [API Documentation](https://apidocs.pingidentity.com/pingone/platform/v1/api/#credentialing-fields-filesupport-types)
```shell
TF_LOG=WARN TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run TestAccCredentialType_ github.com/pingidentity/terraform-provider-pingone/internal/service/credentials
```
```shell
=== RUN   TestAccCredentialType_RemovalDrift
=== PAUSE …
```
> 430-Added support for images in a verifiable credential configuration.

- .changelog/586.txt
- internal/service/base/resource_gateway.go
- internal/service/base/resource_gateway_test.go
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccGateway_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccGateway_RemovalDrift
=== PAUSE TestAccGateway_RemovalDrift
=== RUN   TestAccGateway_NewEnv
=== PAUSE TestAccGateway_NewEnv
=== RUN   TestAccGateway_Full
=== PAUSE TestAccGateway_Full
=== RUN   TestAccGateway_Minimal
=== PAUSE TestAccGateway_Minimal
=== RUN   TestAccGateway_Change
=== PAUSE TestAccGateway_Change
=== RUN   TestAccGateway_PF
=== PAUSE TestAccGateway_PF
=== RUN   TestAccGateway_APIG
=== PAUSE TestAccGateway_APIG
=== RUN   TestAccGateway_Intelligence
=== PAUSE TestAccGateway_Intelligence
=== RUN   TestAccGateway_LDAP
=== PAUSE TestAccGateway_LDAP
=== RUN   TestAccGateway_RADIUS
=== PAUSE TestAccGateway_RADIUS …
```
> `resource/pingone_gateway`: Fixed incorrect unchanged plan when updating the `user_type` parameter.

- .changelog/590.txt
- internal/service/risk/resource_risk_predictor.go
- `resource/pingone_risk_predictor`: Adjust code to no longer use deprecated API parameter `composition`.  Full support of multiple risk composition policies is planned for a future release.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccRiskPredictor_Composite github.com/pingidentity/terraform-provider-pingone/internal/service/risk
```
```shell
=== RUN   TestAccRiskPredictor_Composite
=== PAUSE TestAccRiskPredictor_Composite
=== CONT  TestAccRiskPredictor_Composite
--- PASS: TestAccRiskPredictor_Composite (36.35s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/risk        37.158s
```
> Adjust code to no longer use deprecated API parameter `composition`

- .changelog/592.txt
- docs/data-sources/role.md
- internal/provider/sdkv2/provider.go
- internal/service/base/data_source_role.go
- internal/service/base/data_source_role_test.go
- internal/service/base/service.go
- `data-source/pingone_role`: Migrated to plugin framework.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccRoleDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccRoleDataSource_ByNameFull
=== PAUSE TestAccRoleDataSource_ByNameFull
=== RUN   TestAccRoleDataSource_NotFound
=== PAUSE TestAccRoleDataSource_NotFound
=== CONT  TestAccRoleDataSource_ByNameFull
=== CONT  TestAccRoleDataSource_NotFound
--- PASS: TestAccRoleDataSource_NotFound (1.18s)
--- PASS: TestAccRoleDataSource_ByNameFull (29.90s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        30.901s
```
> `data-source/pingone_role`: Migrate to plugin framework

- .changelog/597.txt
- internal/service/verify/resource_verify_voice_phrase_content_test.go
`pingone_verify_voice_phrase_content`: Fix constraint violation error in replace voice phrase test. 
Collision occurred due to duplicate `display_name` encountered after downstream API change that now correctly enforces unique display_name values.
```shell
TF_LOG=WARN TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s  -run TestAccVerifyVoicePhraseContent_ github.com/pingidentity/terraform-provider-pingone/internal/service/verify
```
```shell
=== RUN   TestAccVerifyVoicePhraseContent_RemovalDrift
=== PAUSE TestAccVerifyVoicePhraseContent_RemovalDrift
=== RUN   TestAccVerifyVoicePhraseContent_NewEnv
=== PAUSE TestAccVerifyVoicePhraseContent_NewEnv
=== RUN   TestAccVerifyVoicePhraseContent_Full
=== PAUSE TestAccVerifyVoicePhraseContent_Full
=== RUN …
```
> `pingone_verify_voice_phrase_content`: Fix constraint violation error in voice phrase replacement test.

- .changelog/603.txt
- docs/resources/application_role_assignment.md
- docs/resources/gateway.md
- docs/resources/gateway_role_assignment.md
- docs/resources/population.md
- docs/resources/role_assignment_user.md
- examples/resources/pingone_application_role_assignment/resource-population.tf
- examples/resources/pingone_gateway/resource-ldap.tf
- examples/resources/pingone_gateway_role_assignment/resource-population.tf
- examples/resources/pingone_population/resource.tf
- examples/resources/pingone_role_assignment_user/resource-population.tf
- internal/acctest/acctest.go
- internal/service/base/data_source_environment_test.go
- internal/service/base/data_source_environments_test.go
- internal/service/base/resource_gateway_role_assignment_test.go
- internal/service/credentials/data_source_credential_issuer_profile_test.go
- Remove deprecated default population params from examples and tests
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironmentsDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironmentDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccRoleAssignmentGateway_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccCredentialIssuerProfileDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/credentials
```
```shell
=== RUN   TestAccEnvironmentsDataSource_BySCIMFilter
=== PAUSE …
```
> Remove deprecated default population params from examples and tests

- .changelog/629.txt
- docs/guides/version-1-upgrade.md
- docs/resources/environment.md
- internal/service/base/resource_environment.go
- internal/service/base/resource_environment_test.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_environment`: Removal of deprecated parameter `default_population` and computed attribute `default_population_id`.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== PAUSE TestAccEnvironment_DeleteProductionEnvironmentProtection
=== RUN …
```
> `resource/pingone_environment`: Removal of deprecated parameter `default_population` and computed attribute `default_population_id` (`v1.0.0`)

- .changelog/630.txt
- docs/guides/version-1-upgrade.md
- docs/resources/mfa_application_push_credential.md
- internal/service/mfa/resource_application_push_credential.go
- internal/service/mfa/resource_application_push_credential_test.go
- templates/guides/version-1-upgrade.md
- templates/resources/mfa_application_push_credential.md.tmpl
- `resource/pingone_mfa_application_push_credential`: Removal of deprecated parameter `fcm.key`
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccApplicationPushCredential_ github.com/pingidentity/terraform-provider-pingone/internal/service/mfa
```
```shell
=== RUN   TestAccApplicationPushCredential_RemovalDrift
=== PAUSE TestAccApplicationPushCredential_RemovalDrift
=== RUN   TestAccApplicationPushCredential_FCM
=== PAUSE TestAccApplicationPushCredential_FCM
=== RUN   TestAccApplicationPushCredential_APNS
=== PAUSE TestAccApplicationPushCredential_APNS
=== RUN   TestAccApplicationPushCredential_HMS
=== PAUSE TestAccApplicationPushCredential_HMS
=== RUN   TestAccApplicationPushCredential_Change
=== PAUSE TestAccApplicationPushCredential_Change
=== RUN …
```
> `resource/pingone_mfa_application_push_credential`: Removal of deprecated parameter `fcm.key` (`v1.0.0`)

- .changelog/600-2.txt
- docs/resources/population_default.md
- internal/acctest/acctest.go
- internal/service/sso/resource_population_default.go
- internal/service/sso/resource_population_default_test.go
- `resource/pingone_population_default`: Fix timeout logic
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccPopulationDefault_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccPopulationDefault_RemovalDrift
=== PAUSE TestAccPopulationDefault_RemovalDrift
=== RUN   TestAccPopulationDefault_Full
=== PAUSE TestAccPopulationDefault_Full
=== RUN   TestAccPopulationDefault_Minimal
=== PAUSE TestAccPopulationDefault_Minimal
=== RUN   TestAccPopulationDefault_BadParameters
=== PAUSE TestAccPopulationDefault_BadParameters
=== CONT  TestAccPopulationDefault_RemovalDrift
=== CONT  TestAccPopulationDefault_Minimal
=== CONT  TestAccPopulationDefault_Full
=== CONT  TestAccPopulationDefault_BadParameters
--- PASS: …
```
> `resource/pingone_population_default`: Fix timeout logic

- .changelog/640.txt
- docs/resources/environment.md
- docs/resources/population_default.md
- internal/service/base/resource_environment.go
- internal/service/base/resource_environment_test.go
- internal/service/sso/resource_population_default.go
- `resource/pingone_environment`: Fixed ineffectual `timeouts` block configuration.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== PAUSE TestAccEnvironment_DeleteProductionEnvironmentProtection
=== RUN   TestAccEnvironment_DeleteProductionEnvironment
=== PAUSE …
```
> Adjustments to default population user-configurable timeouts

- .changelog/600.txt
- CHANGELOG.md
- docs/resources/population_default.md
- internal/acctest/acctest.go
- internal/service/base/resource_environment.go
- internal/service/base/resource_environment_test.go
- internal/service/sso/resource_population_default.go
- internal/service/sso/resource_population_default_test.go
- Revert unreleased change that removed default environment creation from the `pingone_environment` resource
- Revert unreleased changes for timeout configuration on the `pingone_population_default` resource
- Revert bug fix for default population creation conflict when the DaVinci service is added to the `pingone_environment` resource
> Align provider to bootstrap routine

- .changelog/643.txt
- docs/guides/version-1-upgrade.md
- docs/resources/environment.md
- internal/service/base/resource_environment.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_environment`: Remove `timeout` parameter block
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== PAUSE TestAccEnvironment_DeleteProductionEnvironmentProtection
=== RUN   TestAccEnvironment_DeleteProductionEnvironment
=== PAUSE TestAccEnvironment_DeleteProductionEnvironment
=== …
```
> `resource/pingone_environment`: Remove `timeouts` parameter block

- .changelog/645.txt
- docs/guides/version-1-upgrade.md
- docs/resources/mfa_settings.md
- internal/service/mfa/resource_mfa_settings.go
- internal/service/mfa/resource_mfa_settings_test.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_mfa_settings`: Removal of deprecated parameter `authentication`.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccMFASettings_ github.com/pingidentity/terraform-provider-pingone/internal/service/mfa
```
```shell
=== RUN   TestAccMFASettings_RemovalDrift
=== PAUSE TestAccMFASettings_RemovalDrift
=== RUN   TestAccMFASettings_Full
=== PAUSE TestAccMFASettings_Full
=== RUN   TestAccMFASettings_Minimal
=== PAUSE TestAccMFASettings_Minimal
=== RUN   TestAccMFASettings_Change
=== PAUSE TestAccMFASettings_Change
=== RUN   TestAccMFASettings_BadParameters
=== PAUSE TestAccMFASettings_BadParameters
=== CONT  TestAccMFASettings_RemovalDrift
=== CONT  TestAccMFASettings_Change
=== CONT  TestAccMFASettings_Minimal
=== CONT  TestAccMFASettings_Full
=== CONT …
```
> `resource/pingone_mfa_settings`: Removal of deprecated parameter `authentication`

- .changelog/652.txt
- internal/service/base/resource_environment.go
- internal/service/base/resource_environment_test.go
- `resource/pingone_environment`: Fixed `Value Conversion Error` when attempting to create an environment using calculated `service` blocks.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== PAUSE …
```
> `resource/pingone_environment`: Fixed `Value Conversion Error` when attempting to create an environment using calculated (unknown) `service` blocks.

- .changelog/657.txt
- docs/guides/version-1-upgrade.md
- docs/resources/application_resource_grant.md
- internal/service/sso/resource_application_resource_grant.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_resource_grant`: Changed parameters `resource_id` and `scopes` to be read-only.
- 
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccApplicationResourceGrant_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccApplicationResourceGrant_RemovalDrift
=== PAUSE TestAccApplicationResourceGrant_RemovalDrift
=== RUN   TestAccApplicationResourceGrant_SystemApplication
=== PAUSE TestAccApplicationResourceGrant_SystemApplication
=== RUN …
```
> `resource/pingone_resource_grant`: Changed parameters `resource_id` and `scopes` to be read-only (`v1.0.0`)

- .changelog/658.txt
- docs/guides/version-1-upgrade.md
- docs/resources/resource_attribute.md
- internal/service/sso/resource_resource_attribute.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_resource_attribute`: Changed parameter `resource_id` to be read-only
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccResourceAttribute_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccResourceAttribute_RemovalDrift
=== PAUSE TestAccResourceAttribute_RemovalDrift
=== RUN   TestAccResourceAttribute_OIDC_Custom
=== PAUSE TestAccResourceAttribute_OIDC_Custom
=== RUN   TestAccResourceAttribute_OIDC_ReservedAttributeName
=== PAUSE TestAccResourceAttribute_OIDC_ReservedAttributeName
=== RUN   TestAccResourceAttribute_OIDC_Predefined
=== PAUSE TestAccResourceAttribute_OIDC_Predefined
=== RUN   TestAccResourceAttribute_Custom
=== PAUSE TestAccResourceAttribute_Custom …
```
> `resource/pingone_resource_attribute`: Changed parameter `resource_id` to be read-only

- .changelog/660.txt
- docs/guides/version-1-upgrade.md
- docs/resources/schema_attribute.md
- internal/service/sso/resource_schema_attribute.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_schema_attribute`: Changed parameter `schema_id` to be read-only
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccSchemaAttribute_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccSchemaAttribute_RemovalDrift
=== PAUSE TestAccSchemaAttribute_RemovalDrift
=== RUN   TestAccSchemaAttribute_NewEnv
=== PAUSE TestAccSchemaAttribute_NewEnv
=== RUN   TestAccSchemaAttribute_String
=== PAUSE TestAccSchemaAttribute_String
=== RUN   TestAccSchemaAttribute_StringEnumeratedValues
=== PAUSE TestAccSchemaAttribute_StringEnumeratedValues
=== RUN   TestAccSchemaAttribute_StringRegexValidation
=== PAUSE TestAccSchemaAttribute_StringRegexValidation
=== RUN …
```
> `resource/pingone_schema_attribute`: Changed parameter `schema_id` to be read-only

- .changelog/662.txt
- docs/guides/version-1-upgrade.md
- docs/resources/identity_provider.md
- docs/resources/identity_provider_attribute.md
- examples/resources/pingone_identity_provider/resource.tf
- examples/resources/pingone_identity_provider_attribute/resource.tf
- internal/framework/schema_attribute_description.go
- internal/service/sso/resource_identity_provider.go
- internal/service/sso/resource_identity_provider_attribute_test.go
- internal/service/sso/resource_identity_provider_test.go
- internal/service/sso/resource_sign_on_policy_action_test.go
- internal/service/sso/resource_user_test.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_identity_provider`: Changed block data types
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccIdentityProvider_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccIdentityProvider_RemovalDrift
=== PAUSE TestAccIdentityProvider_RemovalDrift
=== RUN   TestAccIdentityProvider_NewEnv
=== PAUSE TestAccIdentityProvider_NewEnv
=== RUN   TestAccIdentityProvider_Change
=== PAUSE TestAccIdentityProvider_Change
=== RUN   TestAccIdentityProvider_Facebook
=== PAUSE TestAccIdentityProvider_Facebook
=== RUN   TestAccIdentityProvider_Google
=== PAUSE TestAccIdentityProvider_Google
=== RUN   TestAccIdentityProvider_LinkedIn
=== PAUSE TestAccIdentityProvider_LinkedIn
=== RUN …
```
> `resource/pingone_identity_provider`: Changed block data types

- .changelog/663.txt
- docs/guides/version-1-upgrade.md
- docs/resources/webhook.md
- examples/resources/pingone_webhook/resource.tf
- internal/service/base/resource_webhook.go
- internal/service/base/resource_webhook_test.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_webhook`: Changed the `filter_options` parameter data type.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccWebhook_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccWebhook_RemovalDrift
=== PAUSE TestAccWebhook_RemovalDrift
=== RUN   TestAccWebhook_NewEnv
=== PAUSE TestAccWebhook_NewEnv
=== RUN   TestAccWebhook_Full
=== PAUSE TestAccWebhook_Full
=== RUN   TestAccWebhook_Minimal
=== PAUSE TestAccWebhook_Minimal
=== RUN   TestAccWebhook_Change
=== PAUSE TestAccWebhook_Change
=== RUN   TestAccWebhook_Webhooks
=== PAUSE TestAccWebhook_Webhooks
=== RUN   TestAccWebhook_Populations
=== PAUSE TestAccWebhook_Populations
=== RUN   TestAccWebhook_BadParameters
=== PAUSE …
```
> `resource/pingone_webhook`: Changed block data types

- .changelog/tbc.txt
- docs/data-sources/groups.md
- docs/guides/version-1-upgrade.md
- examples/data-sources/pingone_groups/data-source.tf
- internal/service/sso/data_source_groups.go
- internal/service/sso/data_source_groups_test.go
- templates/guides/version-1-upgrade.md
- `data-source/pingone_groups`: Changed the `data_filter` parameter data type and renamed to `data_filters`.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccGroupsDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccGroupsDataSource_BySCIMFilter
=== PAUSE TestAccGroupsDataSource_BySCIMFilter
=== RUN   TestAccGroupsDataSource_ByDataFilter
=== PAUSE TestAccGroupsDataSource_ByDataFilter
=== RUN   TestAccGroupsDataSource_NotFound
=== PAUSE TestAccGroupsDataSource_NotFound
=== CONT  TestAccGroupsDataSource_BySCIMFilter
=== CONT  TestAccGroupsDataSource_NotFound
=== CONT  TestAccGroupsDataSource_ByDataFilter
--- PASS: TestAccGroupsDataSource_NotFound (6.45s)
--- PASS: …
```
> `data-source/pingone_groups`: Changed the data_filter parameter data type and renamed to data_filters (`v1`)

- .changelog/682.txt
- docs/data-sources/application.md
- docs/guides/version-1-upgrade.md
- internal/service/sso/data_source_application.go
- templates/guides/version-1-upgrade.md
- Changed the `access_control_group_options` attribute data type.
- Changed the `external_link_options` attribute data type.
- Changed the `icon` attribute data type.
- Changed the `oidc_options` attribute data type.
- Changed the `oidc_options.certificate_based_authentication` attribute data type.
- Changed the `oidc_options.cors_settings` attribute data type.
- Changed the `oidc_options.mobile_app` attribute data type.
- Changed the `oidc_options.mobile_app.integrity_detection` attribute data type.
- Changed the `oidc_options.mobile_app.integrity_detection.cache_duration` attribute data type.
- Changed the `oidc_options.mobile_app.integrity_detection.google_play` attribute data type.
- Changed the `saml_options` attribute data type.
- Changed the `saml_options.cors_settings` attribute …
> Changed `pingone_application` data source data types

- .changelog/704.txt
- .github/workflows/acceptance-test-ff-multi-version.yml
- .github/workflows/acceptance-test-multi-version.yml
- README.md
- docs/resources/form.md
- internal/service/base/resource_form.go
- internal/service/base/resource_form_test.go
- internal/service/sso/resource_user.go
- Address `pingone_form` plan inconsistency issues on Terraform versions `< 1.6` (no changelog needed)
- Address `pingone_user` plan inconsistency issues on Terraform versions `< 1.4`
- Raise minimum terraform version from `v1.1` to `v1.3` to avoid plan inconsistency issues in earlier versions of Terraform
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccForm_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccUser github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccForm_RemovalDrift
=== PAUSE TestAccForm_RemovalDrift
=== RUN   TestAccForm_NewEnv
=== PAUSE TestAccForm_NewEnv
=== RUN   TestAccForm_Full
=== PAUSE …
```
> Address Terraform minimum version compatibility issues

- .changelog/715.txt
- docs/resources/form.md
- internal/service/base/resource_form.go
- internal/service/base/resource_form_test.go
- `resource/pingone_form`: Fixed "Provider produced inconsistent result after apply" error when configuring `PASSWORD` or `PASSWORD_VERIFY` type form controls with the `validation` parameter set.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccForm_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccForm_RemovalDrift
=== PAUSE TestAccForm_RemovalDrift
=== RUN   TestAccForm_NewEnv
=== PAUSE TestAccForm_NewEnv
=== RUN   TestAccForm_Full
=== PAUSE TestAccForm_Full
=== RUN   TestAccForm_Multiple
=== PAUSE TestAccForm_Multiple
=== RUN   TestAccForm_FieldCheckbox
=== PAUSE TestAccForm_FieldCheckbox
=== RUN   TestAccForm_FieldCombobox
=== PAUSE TestAccForm_FieldCombobox
=== RUN …
```
> Fix "Provider produced inconsistent result after apply" error

- .changelog/721.txt
- internal/service/sso/resource_sign_on_policy_action.go
- internal/service/sso/resource_sign_on_policy_action_test.go
- Corrected the "login" sign on policy action error messages when configuring a gateway with missing configuration
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccSignOnPolicyAction_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccSignOnPolicyAction_RemovalDrift
=== PAUSE TestAccSignOnPolicyAction_RemovalDrift
=== RUN   TestAccSignOnPolicyAction_LoginAction
=== PAUSE TestAccSignOnPolicyAction_LoginAction
=== RUN   TestAccSignOnPolicyAction_LoginAction_Gateway
=== PAUSE TestAccSignOnPolicyAction_LoginAction_Gateway
=== RUN   TestAccSignOnPolicyAction_IDFirstAction
=== PAUSE TestAccSignOnPolicyAction_IDFirstAction
=== RUN   TestAccSignOnPolicyAction_MFAAction
=== PAUSE …
```
> Correct Login SOP action error when mapping LDAP gateways for PingOne user lookup

- .changelog/728.txt
- docs/data-sources/licenses.md
- internal/provider/sdkv2/provider.go
- internal/service/base/data_source_licenses.go
- internal/service/base/service.go
- `data-source/pingone_licenses`: Migrate to plugin framework
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccLicensesDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccLicensesDataSource_BySCIMFilter
=== PAUSE TestAccLicensesDataSource_BySCIMFilter
=== RUN   TestAccLicensesDataSource_ByDataFilter
=== PAUSE TestAccLicensesDataSource_ByDataFilter
=== RUN   TestAccLicensesDataSource_NotFound
=== PAUSE TestAccLicensesDataSource_NotFound
=== CONT  TestAccLicensesDataSource_BySCIMFilter
=== CONT  TestAccLicensesDataSource_NotFound
=== CONT  TestAccLicensesDataSource_ByDataFilter
--- PASS: TestAccLicensesDataSource_BySCIMFilter (3.67s)
--- PASS: …
```
> `data-source/pingone_licenses`: Migrate to plugin framework

- .changelog/740.txt
- docs/resources/password_policy.md
- internal/service/sso/resource_password_policy.go
- internal/service/sso/resource_password_policy_test.go
As of 11 March 2022, password set by API can be between 8 and 32 characters (inclusive).  Updated the validation rule in the `pingone_password_policy` resource
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccPasswordPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccPasswordPolicy_RemovalDrift
=== PAUSE TestAccPasswordPolicy_RemovalDrift
=== RUN   TestAccPasswordPolicy_NewEnv
=== PAUSE TestAccPasswordPolicy_NewEnv
=== RUN   TestAccPasswordPolicy_Full
=== PAUSE TestAccPasswordPolicy_Full
=== RUN   TestAccPasswordPolicy_Minimal
=== PAUSE TestAccPasswordPolicy_Minimal
=== RUN   TestAccPasswordPolicy_BadParameters
=== PAUSE TestAccPasswordPolicy_BadParameters
=== CONT …
```
> `resource/pingone_password_policy`: Update minimum password length validation

- .changelog/747.txt
- docs/resources/notification_policy.md
- docs/resources/sign_on_policy.md
- examples/resources/pingone_notification_policy/resource-environment.tf
- examples/resources/pingone_notification_policy/resource-unlimited.tf
- examples/resources/pingone_notification_policy/resource-user.tf
- internal/provider/sdkv2/provider.go
- internal/service/base/resource_key.go
- internal/service/base/resource_notification_policy.go
- internal/service/mfa/resource_fido2_policy.go
- internal/service/risk/resource_risk_policy.go
- internal/service/sso/resource_sign_on_policy.go
- internal/service/sso/resource_sign_on_policy_test.go
- internal/service/sso/service.go
- internal/service/verify/resource_verify_policy.go
- `resource/pingone_sign_on_policy`: Migrated to plugin framework.
- `resource/pingone_notification_policy`: Corrected documentation HCL examples.
- `resource/pingone_key`: Fixed unnecessary replacement plan when certain properties are modified.
- `resource/pingone_notification_policy`: The resource can now be modified with Terraform if the `default` property is modified to `true` in the console or by API directly.
- `resource/pingone_mfa_fido2_policy`: Resource can now be modified with Terraform if the `default` property is modified to `true` in the console or by API directly.
- `resource/pingone_risk_policy`: Resource can now be modified with Terraform if the `default` property is modified to `true` in the console or by API directly.
- `resource/pingone_sign_on_policy`: Resource can now …
> Allow resources to be modified with Terraform if the `default` property is modified to `true`

- .changelog/748.txt
- internal/service/risk/data_source_risk_predictors.go
- internal/service/risk/resource_risk_policy.go
- `resource/pingone_risk_policy`: Fixed "Cannot find risk predictor from compact name" error when applying a policy containing "bot detection", "new device" or "adversary in the middle" predictors.
- `resource/pingone_risk_policy`: Provider now waits for confirmation that, on destroy, the risk policy has been successfully removed in the environment.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccRiskPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/risk
```
**Note** Testing includes workaround for state inconsistency issue raised in STAGING-22374
<details>
```shell
=== RUN   TestAccRiskPolicy_RemovalDrift
=== PAUSE TestAccRiskPolicy_RemovalDrift
=== RUN   TestAccRiskPolicy_NewEnv
=== PAUSE TestAccRiskPolicy_NewEnv …
```
> Fix "Cannot find risk predictor from compact name" error

- .changelog/751.txt
- internal/service/risk/resource_risk_policy.go
- internal/service/risk/resource_risk_policy_test.go
- `resource/pingone_risk_policy`: Fixed unconfigured predictors (predictors not configured in the policy) are included with a weight/score of 0.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccRiskPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/ris
```
**Note** Testing includes workaround for state inconsistency issue raised in STAGING-22374
<details>
```shell
=== RUN   TestAccRiskPolicy_RemovalDrift
=== PAUSE TestAccRiskPolicy_RemovalDrift
=== RUN   TestAccRiskPolicy_NewEnv
=== PAUSE TestAccRiskPolicy_NewEnv
=== RUN   TestAccRiskPolicy_Full
=== PAUSE TestAccRiskPolicy_Full
=== RUN   TestAccRiskPolicy_Scores
=== PAUSE TestAccRiskPolicy_Scores
=== RUN   TestAccRiskPolicy_Weights
=== PAUSE TestAccRiskPolicy_Weights …
```
> `resource/pingone_risk_policy`: Fix unconfigured predictors with weight/score of 0

- .changelog/752.txt
- docs/resources/credential_issuer_profile.md
- internal/service/credentials/resource_credential_issuer_profile.go
- `resource/pingone_credential_issuer_profile`: Fixed race condition leading to a "A resource with the specified name already exists" error when creating a credential issuer profile at the same time as creating a new environment.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccCredential github.com/pingidentity/terraform-provider-pingone/internal/service/credentials
```
<details>
```shell
=== RUN   TestAccCredentialIssuanceRuleDataSource_ByIDFull
=== PAUSE TestAccCredentialIssuanceRuleDataSource_ByIDFull
=== RUN   TestAccCredentialIssuanceRuleDataSource_NotFound
=== PAUSE TestAccCredentialIssuanceRuleDataSource_NotFound
=== RUN   TestAccCredentialIssuanceRuleDataSource_InvalidConfig
=== PAUSE …
```
> Fix "resource with the specified name already exists" error

- .changelog/754.txt
- docs/data-sources/verify_policy.md
- docs/resources/verify_policy.md
- internal/service/verify/data_source_verify_policy.go
- internal/service/verify/data_source_verify_policy_test.go
- internal/service/verify/resource_verify_policy.go
- internal/service/verify/resource_verify_policy_test.go
```release-note:enhancement
```release-note:enhancement
`resource/pingone_verify_policy`: Added support for `inspection_type` property in `government_id` configuration object.
```
```release-note:enhancement
`data_source/pingone_verify_policy`: Added support for `inspection_type` property in `government_id` configuration object.
```
```
N/A
```shell
TF_LOG=INFO TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s  -run TestAccVerifyPolicy github.com/pingidentity/terraform-provider-pingone/internal/service/verify
```
<details>
```shell
% TF_LOG=INFO TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s  -run TestAccVerifyPolicy github.com/pingidentity/terraform-provider-pingone/internal/service/verify
=== RUN …
```
> `pingone_verify_policy`: add support for `inspection_type` property in `government_id` configuration object.

- .changelog/770.txt
- internal/service/sso/resource_user.go
- internal/service/sso/resource_user_test.go
- `resource/pingone_user`: Fixed error when attempting to move a user between populations by changing the `population_id` value.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccUser_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccUser_RemovalDrift
=== PAUSE TestAccUser_RemovalDrift
=== RUN   TestAccUser_NewEnv
=== PAUSE TestAccUser_NewEnv
=== RUN   TestAccUser_All
=== PAUSE TestAccUser_All
=== RUN   TestAccUser_AllWithoutReplacement
=== PAUSE TestAccUser_AllWithoutReplacement
=== RUN   TestAccUser_AccountLocked
=== PAUSE TestAccUser_AccountLocked
=== RUN   TestAccUser_ChangePopulation
=== PAUSE TestAccUser_ChangePopulation
=== RUN   TestAccUser_ChangeMFA
=== PAUSE …
```
> Fix error when attempting to move a user between populations

- .changelog/771.txt
- go.mod
- go.sum
- go.work.sum
- bump `github.com/hashicorp/terraform-plugin-framework` 1.6.1 => 1.7.0
- bump `github.com/patrickcping/pingone-go-sdk-v2` 0.11.7 => 0.11.8
- bump `github.com/patrickcping/pingone-go-sdk-v2/risk` 0.14.0 => 0.14.1
N/a
Deferred to nightly tests
> bump modules 2024-03-25

- .changelog/773.txt
- docs/index.md
- examples/provider/provider-global-options.tf
- examples/provider/provider.tf
- internal/acctest/acctest.go
- internal/acctest/service/sso/user.go
- internal/client/client.go
- internal/client/config.go
- internal/provider/framework/provider.go
- internal/provider/sdkv2/provider.go
- internal/service/base/resource_environment.go
- internal/service/sso/resource_population.go
- internal/service/sso/resource_population_test.go
- internal/sweep/sweep.go
- templates/index.md.tmpl
- Added `global_options` provider parameter block to be able to override specific API behaviours.
- Added the `global_options.population.contains_users_force_delete` provider parameter to be able to force-delete populations if they contain users in sandbox environments.  Use of this provider option may result in loss of user data - use with caution.
- Deprecated the `force_delete_production_type` provider parameter.  This parameter will be removed in the next major release.  Please use the `global_options.population.contains_users_force_delete` provider parameter going forward.  Use of this provider option may result in loss of user data - use with caution.
- `resource/pingone_environment`: Code optimisation on plan modification.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run …
```
> Add global options to provider configuration, including the ability to force delete populations if they contain users

- .changelog/782.txt
- internal/service/base/resource_notification_settings_email.go
- `resource/pingone_notification_settings_email`: Fixed panic crash when attempting to import environment default notification email settings.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccNotificationSettingsEmail_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationSettingsEmail_RemovalDrift
=== PAUSE TestAccNotificationSettingsEmail_RemovalDrift
=== RUN   TestAccNotificationSettingsEmail_Full
=== PAUSE TestAccNotificationSettingsEmail_Full
=== RUN   TestAccNotificationSettingsEmail_EmailSources
=== PAUSE TestAccNotificationSettingsEmail_EmailSources
=== RUN   TestAccNotificationSettingsEmail_BadParameters
=== PAUSE TestAccNotificationSettingsEmail_BadParameters
=== …
```
> `resource/pingone_notification_settings_email`: Fix panic crash when attempting to import environment default notification email settings

- .changelog/784.txt
- go.mod
- go.sum
- internal/framework/resource.go
- internal/service/base/data_source_agreement.go
- internal/service/base/resource_agreement_localization_revision.go
- internal/service/base/resource_custom_domain.go
- internal/service/base/resource_custom_domain_ssl.go
- internal/service/base/resource_key.go
- internal/service/base/resource_key_rotation_policy.go
- internal/service/base/resource_notification_settings.go
- internal/service/base/resource_phone_delivery_settings.go
- internal/service/credentials/data_source_credential_issuer_profile.go
- internal/service/credentials/data_source_credential_type.go
- internal/service/credentials/resource_credential_issuer_profile.go
- internal/service/credentials/resource_credential_type.go
- internal/service/risk/resource_risk_predictor.go
- internal/service/sso/resource_application_secret.go
- internal/service/sso/utils_application_secret.go
- internal/service/verify/data_source_verify_policy.go
- internal/service/verify/data_source_verify_voice_phrase.go
- internal/service/verify/data_source_verify_voice_phrase_content.go
- internal/service/verify/resource_verify_policy.go
- internal/service/verify/resource_verify_voice_phrase.go
- internal/service/verify/resource_verify_voice_phrase_content.go
Changed date-time fields to use custom RFC3339 data type.
N/a
Deferred to nightly
> Changed date-time fields to use custom RFC3339 data type

- .changelog/786.txt
- docs/guides/version-1-upgrade.md
- docs/resources/custom_domain_verify.md
- internal/service/base/resource_custom_domain_verify.go
- internal/service/base/resource_custom_domain_verify_test.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_custom_domain_verify`: Changed the `timeouts` data types.
- `resource/pingone_custom_domain_verify`: Fixed ineffectual `timeouts` configuration.
N/a
Deferred to RC1
> `resource/pingone_custom_domain_verify`: Fix timeouts param and change data type

- .changelog/796.txt
- docs/guides/version-1-upgrade.md
- docs/resources/notification_settings_email.md
- examples/resources/pingone_notification_settings_email/resource.tf
- internal/service/base/resource_notification_settings_email.go
- internal/service/base/resource_notification_settings_email_test.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_notification_settings_email`: Changed the `from` and `reply_to` data types.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccNotificationSettingsEmail_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationSettingsEmail_RemovalDrift
=== PAUSE TestAccNotificationSettingsEmail_RemovalDrift
=== RUN   TestAccNotificationSettingsEmail_Full
=== PAUSE TestAccNotificationSettingsEmail_Full
=== RUN   TestAccNotificationSettingsEmail_EmailSources
=== PAUSE TestAccNotificationSettingsEmail_EmailSources
=== RUN   TestAccNotificationSettingsEmail_BadParameters
=== PAUSE TestAccNotificationSettingsEmail_BadParameters
=== CONT …
```
> `resource/pingone_notification_settings_email`: Change the `from` and `reply_to` data types

- .changelog/797.txt
- docs/guides/version-1-upgrade.md
- docs/resources/mfa_settings.md
- examples/resources/pingone_mfa_settings/resource.tf
- internal/provider/sdkv2/provider.go
- internal/service/mfa/resource_mfa_settings.go
- internal/service/mfa/resource_mfa_settings_test.go
- internal/service/mfa/service.go
- templates/guides/version-1-upgrade.md
- Migrated to plugin framework.
- Breaking change: `resource/pingone_mfa_settings`: Changed the `pairing` and `lockout` data types.
- Breaking change: Removed `phone_extensions_enabled` and moved into nested attribute object.  Use `phone_extensions.enabled` going forward.
- Enhancement: Added `users.mfa_enabled` that, when set to `true`, will enable MFA by default for new users.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccMFASettings_ github.com/pingidentity/terraform-provider-pingone/internal/service/mfa
```
<details>
```shell
=== RUN   TestAccMFASettings_RemovalDrift
=== PAUSE TestAccMFASettings_RemovalDrift
=== RUN   TestAccMFASettings_Full
=== PAUSE TestAccMFASettings_Full
=== RUN   TestAccMFASettings_Minimal
=== PAUSE …
```
> `resource/pingone_mfa_settings`: Migrate to framework and change data types

- .changelog/829.txt
- docs/resources/identity_provider.md
- internal/service/sso/resource_identity_provider.go
- internal/service/sso/resource_identity_provider_test.go
- `resource/pingone_identity_provider`: Added the `pkce_method` property for OIDC Identity Providers.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccIdentityProvider_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccIdentityProvider_RemovalDrift
=== PAUSE TestAccIdentityProvider_RemovalDrift
=== RUN   TestAccIdentityProvider_NewEnv
=== PAUSE TestAccIdentityProvider_NewEnv
=== RUN   TestAccIdentityProvider_Change
=== PAUSE TestAccIdentityProvider_Change
=== RUN   TestAccIdentityProvider_Facebook
=== PAUSE TestAccIdentityProvider_Facebook
=== RUN   TestAccIdentityProvider_Google
=== PAUSE TestAccIdentityProvider_Google
=== RUN   TestAccIdentityProvider_LinkedIn
=== PAUSE …
```
> `resource/pingone_identity_provider`: Add the `pkce_method` property for OIDC Identity Providers

- .changelog/830.txt
- docs/guides/version-1-upgrade.md
- docs/resources/identity_provider.md
- internal/service/sso/resource_identity_provider.go
- internal/service/sso/resource_identity_provider_test.go
- templates/guides/version-1-upgrade.md
- **Enhancement** - `resource/pingone_identity_provider`: Added ability to set the SP signing key algorithm.
- **Breaking change** - `resource/pingone_identity_provider`: Replaced `saml.sp_signing_key_id` with `saml.sp_signing.key.id`.
- **Breaking change** - `resource/pingone_identity_provider`: Replaced `saml.idp_verification_certificate_ids` with `saml.idp_verification.certificates.*.id`.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccIdentityProvider_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccIdentityProvider_RemovalDrift
=== PAUSE TestAccIdentityProvider_RemovalDrift
=== RUN   TestAccIdentityProvider_NewEnv
=== PAUSE TestAccIdentityProvider_NewEnv
=== RUN …
```
> `resource/pingone_identity_provider`: Update SAML sp signing and idp verification schema

- .changelog/837.txt
- docs/guides/version-1-upgrade.md
- docs/resources/notification_template_content.md
- examples/resources/pingone_notification_template_content/resource.tf
- internal/provider/sdkv2/provider.go
- internal/service/base/resource_notification_template_content.go
- internal/service/base/resource_notification_template_content_test.go
- internal/service/base/service.go
- templates/guides/version-1-upgrade.md
- `resource/pingone_resource`: Migrated to plugin framework.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccNotificationTemplateContent_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationTemplateContent_RemovalDrift
=== PAUSE TestAccNotificationTemplateContent_RemovalDrift
=== RUN   TestAccNotificationTemplateContent_OverrideDefaultLocale
=== PAUSE TestAccNotificationTemplateContent_OverrideDefaultLocale
=== RUN   TestAccNotificationTemplateContent_NewLocale
=== PAUSE TestAccNotificationTemplateContent_NewLocale
=== RUN   TestAccNotificationTemplateContent_NewVariant
=== PAUSE TestAccNotificationTemplateContent_NewVariant
=== RUN …
```
> Migrate `pingone_notification_template_content` to plugin framework

- .changelog/838.txt
- internal/framework/objectplanmodifier/replace_if_existence_changes.go
- internal/service/risk/resource_risk_predictor.go
`resource/pingone_risk_predictor`: Fixed issue that forced replacement of a resource if a mutable field changed within a "resource type" object.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccRiskPredictor_ github.com/pingidentity/terraform-provider-pingone/internal/service/risk
```
<details>
```shell
=== RUN   TestAccRiskPredictor_RemovalDrift
=== PAUSE TestAccRiskPredictor_RemovalDrift
=== RUN   TestAccRiskPredictor_NewEnv
=== PAUSE TestAccRiskPredictor_NewEnv
=== RUN   TestAccRiskPredictor_Full
=== PAUSE TestAccRiskPredictor_Full
=== RUN   TestAccRiskPredictor_Composite
=== PAUSE TestAccRiskPredictor_Composite
=== RUN   TestAccRiskPredictor_Anonymous_Network
=== PAUSE TestAccRiskPredictor_Anonymous_Network
=== RUN …
```
> Add `RequiresReplaceIfExistenceChanges` custom plan modifier

- .changelog/844.txt
- docs/resources/mfa_device_policy.md
- internal/service/mfa/resource_mfa_device_policy.go
- internal/service/mfa/resource_mfa_device_policy_test.go
- internal/service/verify/resource_verify_policy.go
- **Bug**: `resource/pingone_verify_policy`: Resource can now be modified with Terraform if the `default` property is modified to `true` in the console or by API directly.
- **Bug**: `resource/pingone_mfa_device_policy`: Resource can now be modified with Terraform if the `default` property is modified to `true` in the console or by API directly.
- **Enhancement**: `resource/pingone_mfa_device_policy`: Added the `default` field to track (in state) whether the policy is the default for the environment.
N/a
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccMFADevicePolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/mfa && \
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccVerifyPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/verify …
```
> Changes to support import the default MFA device policy and Verify policy into state

- .changelog/845.txt
- internal/service/base/resource_notification_policy.go
- internal/service/mfa/resource_fido2_policy.go
- internal/service/mfa/resource_mfa_device_policy.go
- internal/service/risk/resource_risk_policy.go
- internal/service/sso/resource_password_policy.go
- internal/service/sso/resource_sign_on_policy.go
- internal/service/verify/resource_verify_policy.go
- **Bug**: `resource/pingone_notification_policy`: Fixed blocking error when attempting to destroy the default notification policy for the environment.  This is now a warning instead of an error.
- **Bug**: `resource/pingone_mfa_fido2_policy`: Fixed blocking error when attempting to destroy the default MFA FIDO2 policy for the environment.  This is now a warning instead of an error.
- **Bug**: `resource/pingone_mfa_device_policy`: Fixed blocking error when attempting to destroy the default MFA device policy for the environment.  This is now a warning instead of an error.
- **Bug**: `resource/pingone_risk_policy`: Fixed blocking error when attempting to destroy the default risk policy for the environment.  This is now a warning instead of an error.
- **Bug**: …
> Fix blocking errors when attempting to destroy default policies

- .changelog/850.txt
- docs/data-sources/group.md
- docs/resources/group.md
- examples/resources/pingone_group/resource.tf
- internal/framework/resource.go
- internal/service/sso/data_source_group.go
- internal/service/sso/data_source_group_test.go
- internal/service/sso/resource_group.go
- internal/service/sso/resource_group_test.go
- **Enhancement**: `resource/pingone_group`: Added `custom_data` field to be able to append custom JSON data to a group.
- **Enhancement**: `data-source/pingone_group`: Added `custom_data` field to be able to read custom JSON data attached to a group.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccGroup_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso && \
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccGroupDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccGroup_RemovalDrift
=== PAUSE TestAccGroup_RemovalDrift
=== RUN   TestAccGroup_NewEnv
=== PAUSE TestAccGroup_NewEnv
=== RUN   TestAccGroup_Full
=== PAUSE TestAccGroup_Full
=== RUN …
```
> Add `custom_data` field to be able to append custom JSON data to a group

- .changelog/852.txt
- internal/service/sso/resource_application_resource_grant_test.go
- internal/service/sso/resource_resource_scope.go
- `resource/pingone_resource_scope`: Fixed blocking errors that result from removing multiple resource scopes that are already assigned to an application.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccApplicationResourceGrant_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccApplicationResourceGrant_RemovalDrift
=== PAUSE TestAccApplicationResourceGrant_RemovalDrift
=== RUN   TestAccApplicationResourceGrant_CustomResource_SimultaneousGrantRemoval
=== …
```
> Add mutex to avoid parallel destroy of resource scopes

- .changelog/854.txt
- internal/service/sso/resource_application_resource_grant_test.go
- internal/service/sso/resource_resource_scope.go
- `resource/pingone_resource_scope`: Fixed blocking errors that result from removing multiple resource scopes that are already assigned to an application.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccApplicationResourceGrant_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso && \
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccResourceScope_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccApplicationResourceGrant_RemovalDrift
=== PAUSE TestAccApplicationResourceGrant_RemovalDrift
=== …
```
> Add mutex to avoid parallel destroy of resource scopes (0.29.1)

- internal/service/sso/data_source_application.go
- internal/service/sso/resource_application.go
- internal/service/sso/resource_application_schema_upgrade_0_to_1.go
- internal/service/sso/utils_application.go
- `resource/pingone_application` v0 to v1 state upgrader
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccApplication_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccApplication_RemovalDrift
=== PAUSE TestAccApplication_RemovalDrift
=== RUN   TestAccApplication_NewEnv
=== PAUSE TestAccApplication_NewEnv
=== RUN   TestAccApplication_OIDCFullWeb
=== PAUSE TestAccApplication_OIDCFullWeb
=== RUN   TestAccApplication_OIDCMinimalWeb
=== PAUSE TestAccApplication_OIDCMinimalWeb
=== RUN   TestAccApplication_OIDCWebUpdate
=== PAUSE TestAccApplication_OIDCWebUpdate
=== RUN   TestAccApplication_OIDCFullNative
=== PAUSE TestAccApplication_OIDCFullNative
=== RUN …
```
> `resource/pingone_application` v0 to v1 state upgrader

- internal/service/mfa/resource_mfa_settings.go
- internal/service/mfa/resource_mfa_settings_schema_upgrade_0_to_1.go
- `resource/pingone_mfa_settings` state upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccMFASettings_ github.com/pingidentity/terraform-provider-pingone/internal/service/mfa
```
<details>
```shell
=== RUN   TestAccMFASettings_RemovalDrift
=== PAUSE TestAccMFASettings_RemovalDrift
=== RUN   TestAccMFASettings_Full
=== PAUSE TestAccMFASettings_Full
=== RUN   TestAccMFASettings_Minimal
=== PAUSE TestAccMFASettings_Minimal
=== RUN   TestAccMFASettings_Change
=== PAUSE TestAccMFASettings_Change
=== RUN   TestAccMFASettings_BadParameters
=== PAUSE TestAccMFASettings_BadParameters
=== CONT  TestAccMFASettings_RemovalDrift
=== CONT  TestAccMFASettings_Change
=== CONT  TestAccMFASettings_BadParameters
=== CONT …
```
> `resource/pingone_mfa_settings` state upgrader v0 to v1

- internal/service/base/resource_notification_settings.go
- internal/service/base/resource_notification_settings_email.go
- internal/service/base/resource_notification_settings_email_schema_upgrade_0_to_1.go
- `resource/pingone_notification_settings_email` state upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccNotificationSettingsEmail_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationSettingsEmail_RemovalDrift
=== PAUSE TestAccNotificationSettingsEmail_RemovalDrift
=== RUN   TestAccNotificationSettingsEmail_Full
=== PAUSE TestAccNotificationSettingsEmail_Full
=== RUN   TestAccNotificationSettingsEmail_EmailSources
=== PAUSE TestAccNotificationSettingsEmail_EmailSources
=== RUN   TestAccNotificationSettingsEmail_BadParameters
=== PAUSE TestAccNotificationSettingsEmail_BadParameters
=== CONT  TestAccNotificationSettingsEmail_RemovalDrift
=== CONT …
```
> `resource/pingone_notification_settings_email` state upgrader v0 to v1

- internal/service/base/resource_notification_template_content.go
- internal/service/base/resource_notification_template_content_schema_upgrade_0_to_1.go
- `resource/pingone_notification_template_content` schema upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccNotificationTemplateContent_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationTemplateContent_RemovalDrift
=== PAUSE TestAccNotificationTemplateContent_RemovalDrift
=== RUN   TestAccNotificationTemplateContent_OverrideDefaultLocale
=== PAUSE TestAccNotificationTemplateContent_OverrideDefaultLocale
=== RUN   TestAccNotificationTemplateContent_NewLocale
=== PAUSE TestAccNotificationTemplateContent_NewLocale
=== RUN   TestAccNotificationTemplateContent_NewVariant
=== PAUSE TestAccNotificationTemplateContent_NewVariant
=== RUN …
```
> `resource/pingone_notification_template_content` schema upgrader v0 to v1

- .changelog/883.txt
- internal/service/base/resource_agreement_localization_revision.go
- `resource/pingone_agreement_localization_revision`: Add buffer time to the revision effective date to avoid blocking error
- **Bug** Fixed intermittent "The revision can not take effect in the past" error when leaving `effective_at` blank.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccAgreementLocalizationRevision_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccAgreementLocalizationRevision_RemovalDrift
=== PAUSE TestAccAgreementLocalizationRevision_RemovalDrift
=== RUN   TestAccAgreementLocalizationRevision_Full
=== PAUSE TestAccAgreementLocalizationRevision_Full
=== RUN   TestAccAgreementLocalizationRevision_BadParameters
=== PAUSE …
```
> `resource/pingone_agreement_localization_revision`: Add buffer time to the revision effective date to avoid blocking error

- .changelog/885.txt
- internal/service/base/resource_system_application.go
- `resource/pingone_system_application`: Fix system application not found error
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccSystemApplication_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccSystemApplication_RemovalDrift
=== PAUSE TestAccSystemApplication_RemovalDrift
=== RUN   TestAccSystemApplication_NewEnv
=== PAUSE TestAccSystemApplication_NewEnv
=== RUN   TestAccSystemApplication_Portal
=== PAUSE TestAccSystemApplication_Portal
=== RUN   TestAccSystemApplication_SelfService
=== PAUSE TestAccSystemApplication_SelfService
=== RUN   TestAccSystemApplication_BadParameters
=== PAUSE TestAccSystemApplication_BadParameters
=== CONT  TestAccSystemApplication_RemovalDrift
=== …
```
> `resource/pingone_system_application`: Fix system application not found error

- .changelog/884.txt
- internal/service/base/resource_language_update.go
- Add retry condition for language enabled race condition
- **Bug**: Fix "The language must be enabled before it is set as the default" error when setting a language as enabled and the environment default.
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccLanguageUpdate_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccLanguageUpdate_RemovalDrift
=== PAUSE TestAccLanguageUpdate_RemovalDrift
=== RUN   TestAccLanguageUpdate_Full
=== PAUSE TestAccLanguageUpdate_Full
=== RUN   TestAccLanguageUpdate_Minimal
=== PAUSE TestAccLanguageUpdate_Minimal
=== RUN   TestAccLanguageUpdate_SystemDefined
=== PAUSE TestAccLanguageUpdate_SystemDefined
=== RUN   TestAccLanguageUpdate_Change
=== PAUSE …
```
> `resource/pingone_language_update`: Add retry condition for language enabled race condition

- .changelog/906.txt
- internal/service/sso/resource_population_default.go
`resource/pingone_population_default`: Suppress warning on creation where the default population for an environment cannot be found.
It is normal behaviour for a default population to not exist when an environment is created from scratch, the resource simply creates the population if one is not found.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccPopulationDefault_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccPopulationDefault_RemovalDrift
=== PAUSE TestAccPopulationDefault_RemovalDrift
=== RUN   TestAccPopulationDefault_Full
=== PAUSE TestAccPopulationDefault_Full
=== RUN   TestAccPopulationDefault_Minimal
=== PAUSE TestAccPopulationDefault_Minimal
=== RUN …
```
> `resource/pingone_population_default`: Suppress warning on creation where the default population for an environment cannot be found

- internal/service/credentials/data_source_credential_issuer_profile_test.go
- Correct credential issuer not found test
Changelog not needed
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccCredentialIssuerProfileDataSource_NotFound github.com/pingidentity/terraform-provider-pingone/internal/service/credentials
```
<details>
```shell
=== RUN   TestAccCredentialIssuerProfileDataSource_NotFound
=== PAUSE TestAccCredentialIssuerProfileDataSource_NotFound
=== CONT  TestAccCredentialIssuerProfileDataSource_NotFound
--- PASS: TestAccCredentialIssuerProfileDataSource_NotFound (6.47s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/credentials 10.487s
```
</details>
> Correct credential issuer not found test

- .changelog/935.txt
- docs/resources/mfa_device_policy.md
- internal/service/mfa/resource_mfa_device_policy.go
- internal/service/mfa/resource_mfa_device_policy_test.go
- `resource/pingone_mfa_device_policy`: Added `[email|sms|voice].otp.otp_length` field to allow admins to specify the length of the OTP displayed to users for SMS, Voice or Email delivery methods.
n/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccMFADevicePolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/mfa
```
<details>
```shell
=== RUN   TestAccMFADevicePolicy_RemovalDrift
=== PAUSE TestAccMFADevicePolicy_RemovalDrift
=== RUN   TestAccMFADevicePolicy_NewEnv
=== PAUSE TestAccMFADevicePolicy_NewEnv
=== RUN   TestAccMFADevicePolicy_SMS_Full
=== PAUSE TestAccMFADevicePolicy_SMS_Full
=== RUN   TestAccMFADevicePolicy_SMS_Minimal
=== PAUSE TestAccMFADevicePolicy_SMS_Minimal
=== RUN   TestAccMFADevicePolicy_SMS_Change
=== …
```
> `pingone_mfa_device_policy`: Add `[email|sms|voice].otp.otp_length` field to allow admins to specify the length of the OTP displayed to users

- .changelog/938.txt
- docs/resources/risk_predictor.md
- internal/service/risk/resource_risk_predictor.go
- internal/service/risk/resource_risk_predictor_test.go
- `resource/pingone_risk_predictor`: Added the `predictor_device.should_validate_payload_signature` field to enforce requirement that the Signals SDK payload be provided as a signed JWT for suspicious device predictors.
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccRiskPredictor_.+Device github.com/pingidentity/terraform-provider-pingone/internal/service/risk
```
<details>
```shell
=== RUN   TestAccRiskPredictor_NewDevice
=== PAUSE TestAccRiskPredictor_NewDevice
=== RUN   TestAccRiskPredictor_NewDevice_OverwriteUndeletable
=== PAUSE TestAccRiskPredictor_NewDevice_OverwriteUndeletable
=== RUN   TestAccRiskPredictor_SuspiciousDevice
=== PAUSE TestAccRiskPredictor_SuspiciousDevice
=== RUN …
```
> `resource/pingone_risk_predictor`: Add the `predictor_device.should_validate_payload_signature` field

- .changelog/952.txt
- docs/resources/risk_predictor.md
- examples/resources/pingone_risk_predictor/resource-composite.tf
- internal/service/risk/resource_risk_predictor.go
- internal/service/risk/resource_risk_predictor_test.go
- `pingone_risk_predictor`: Support multiple root level conditions for composite predictors
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccRiskPredictor_ github.com/pingidentity/terraform-provider-pingone/internal/service/risk
```
<details>
```shell
=== RUN   TestAccRiskPredictor_RemovalDrift
=== PAUSE TestAccRiskPredictor_RemovalDrift
=== RUN   TestAccRiskPredictor_NewEnv
=== PAUSE TestAccRiskPredictor_NewEnv
=== RUN   TestAccRiskPredictor_Full
=== PAUSE TestAccRiskPredictor_Full
=== RUN   TestAccRiskPredictor_Composite
=== PAUSE TestAccRiskPredictor_Composite
=== RUN   TestAccRiskPredictor_Adversary_In_The_Middle
=== PAUSE TestAccRiskPredictor_Adversary_In_The_Middle
=== RUN   TestAccRiskPredictor_Adversary_In_The_Middle_OverwriteUndeletabl …
```
> `pingone_risk_predictor`: Support multiple root level conditions for composite predictors

- .changelog/967.txt
- internal/service/verify/resource_verify_policy.go
- internal/service/verify/resource_verify_policy_test.go
resource/pingone_verify_policy: Fixed the handling of otp default values in the email and phone property objects when verify set to DISABLED.
None.
```shell
TF_LOG=DEBUG TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s  github.com/pingidentity/terraform-provider-pingone/internal/service/verify
```
<details>
```shell
=== RUN   TestAccVerifyPoliciesDataSource_NoFilter
=== PAUSE TestAccVerifyPoliciesDataSource_NoFilter
=== RUN   TestAccVerifyPolicyDataSource_All
=== PAUSE TestAccVerifyPolicyDataSource_All
=== RUN   TestAccVerifyPolicyDataSource_FailureChecks
=== PAUSE TestAccVerifyPolicyDataSource_FailureChecks
=== RUN   TestAccVerifyVoicePhraseContentDataSource_All
=== PAUSE TestAccVerifyVoicePhraseContentDataSource_All
=== RUN …
```
> Fixed the handling of otp default values in the email and phone property objects when verify set to DISABLED.

- .github/workflows/acceptance-test-ff-multi-region.yml
- .github/workflows/acceptance-test-ff-multi-version.yml
- DaVinci related acceptance tests re-enabled
N/a
Deferred to nightly
> re-enable DV testing

- .changelog/998.txt
- internal/provider/sdkv2/provider.go
- **Bug**: Fix `service_endpoints` and `global_options` provider parameters when defined explicitly in the HCL provider configuration.
N/a
Manually tested (No acceptance tests created for this use case)
> Fix `service_endpoints` and `global_options` provider parameters when defined explicitly in the HCL provider configuration

- .changelog/1026.txt
- internal/service/base/resource_custom_domain_verify.go
Updated pingone_custom_domain_verify resource retry logic to use [previously working SDK method](https://github.com/pingidentity/terraform-provider-pingone/blob/f28c27189fa8bcc677f09f8572abcd2f32501350/internal/service/base/resource_custom_domain_verify.go#L159).
N/A
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccCustomDomainVerify_CannotVerifyNXDOMAIN ./internal/service/base --count=1
```
<details>
```shell
=== RUN   TestAccCustomDomainVerify_CannotVerifyNXDOMAIN
=== PAUSE TestAccCustomDomainVerify_CannotVerifyNXDOMAIN
=== CONT  TestAccCustomDomainVerify_CannotVerifyNXDOMAIN
--- PASS: TestAccCustomDomainVerify_CannotVerifyNXDOMAIN (36.22s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        36.838s
``` …
> Fix pingone_custom_domain_verify resource: early verification failure with NXDOMAIN

- .changelog/1027.txt
- docs/resources/notification_settings.md
- docs/resources/notification_settings_email.md
- examples/resources/pingone_notification_settings/resource-custom-twilio.tf
- examples/resources/pingone_notification_settings/resource-ping-smtp.tf
- templates/resources/notification_settings.md.tmpl
- templates/resources/notification_settings_email.md.tmpl
* Update/Add `pingone_notification_settings` resource Example Usage documentation to include both Ping-hosted smtp and Twilio examples.
* Add documentation note `pingone_notification_settings_email` to recommend usage of `pingone_notification_settings` when using Ping-hosted smtp email service.
N/A
N/A
N/A
> Update pingone_notification_settings and pingone_notification_settings resource documentation

- .changelog/1028.txt
- go.work.sum
- internal/service/sso/resource_administrator_security.go
- internal/service/sso/resource_administrator_security_gen_test.go
Fix validation of `identity_provider` in the `pingone_admin_security` resource
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccAdministratorSecurity_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
% TF_ACC=1 go test -v -timeout 3000s -run ^TestAccAdministratorSecurity_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
=== RUN   TestAccAdministratorSecurity_RemovalDrift
=== PAUSE TestAccAdministratorSecurity_RemovalDrift
=== RUN   TestAccAdministratorSecurity_MinimalMaximal
--- PASS: TestAccAdministratorSecurity_MinimalMaximal (22.94s)
=== RUN   TestAccAdministratorSecurity_NewEnvPingOne
=== PAUSE TestAccAdministratorSecurity_NewEnvPingOne
=== RUN …
```
> Fix pingone_admin_security resource validation for identity_provider

- internal/service/base/resource_environment_test.go
The TestAccEnvironment_NonCompatibleRegion acceptance test is failing in the AP region because, unlike other regions, it returns 2 region codes ([AP AU]) rather than one [NA], [EU], etc.
This change updates the regex line in the test to account for this possibility, and will match
- [AU]
- [NA]
- [AU AP]
- [AP AU]
- [AU XX]
- [XX AU]
none
```shell
go test -timeout 30s -run ^TestAccEnvironment_NonCompatibleRegion$ github.com/pingidentity/terraform-provider-pingone/internal/service/base -v
```
<details>
```shell
=== CONT  TestAccEnvironment_NonCompatibleRegion
--- PASS: TestAccEnvironment_NonCompatibleRegion (3.84s)
PASS
ok …
```
> Update TestAccEnvironment_NonCompatibleRegion regex

- .changelog/1042.txt
- docs/data-sources/gateway.md
- internal/service/base/data_source_gateway.go
- internal/service/base/data_source_gateway_test.go
FIX: 
*  corrected validation for `radius_davinci_policy_id` when using `RADIUS` type in `pingone_gateway` data source
```shell
TF_ACC=1 go test -v -timeout 240s -run "TestAccGatewayDataSource_FindRADIUS" -count=1 ./internal/service/base
```
<details>
```shell
=== RUN   TestAccGatewayDataSource_FindRADIUSGatewayByID
=== PAUSE TestAccGatewayDataSource_FindRADIUSGatewayByID
=== RUN   TestAccGatewayDataSource_FindRADIUSGatewayByName
=== PAUSE TestAccGatewayDataSource_FindRADIUSGatewayByName
=== CONT  TestAccGatewayDataSource_FindRADIUSGatewayByID
=== CONT  TestAccGatewayDataSource_FindRADIUSGatewayByName
--- PASS: TestAccGatewayDataSource_FindRADIUSGatewayByID (4.03s)
--- PASS: TestAccGatewayDataSource_FindRADIUSGatewayByName (4.13s)
PASS
ok …
```
> correct radius_davinci_policy_id type in pingone_gateway data source

- .changelog/1054.txt
- internal/verify/validate.go
- internal/verify/validate_test.go
Issues in the schema regex validators using `IsURLWithHTTPorHTTPS` and `IsURLWithHTTPS` regex strings meant that URLs that should allow `localhost` were not being allowed, neither any URL with a port defined in the URL (see attached issue).
This bug fix allows URLs to have `localhost` as the hostname and custom ports to be applied, as the console permits.
N/a
```shell
go test -run ^TestRegex_ ./internal/verify
```
<details>
```shell
ok      github.com/pingidentity/terraform-provider-pingone/internal/verify      0.578s
```
</details>
> Corrected url validation to include `localhost` and custom port combinations

- .changelog/1053.txt
- docs/resources/application_flow_policy_assignment.md
- examples/resources/pingone_application_flow_policy_assignment/resource.tf
- `resource/pingone_application_flow_policy_assignment`: Corrected documented HCL example to avoid deprecated fields on the DaVinci provider's `davinci_application` resource.
N/a
N/a - no acceptance tests impacted
> Correct `pingone_application_flow_policy_assignment` HCL example

- .changelog/1061.txt
- internal/service/sso/utils_application.go
Added validation for `saml_options.type` to disallow `TEMPLATE_APP` used for Catalog Applications.
Required SDK Upgrades
N/A
Testing
N/a - no acceptance tests impacted
> `resource/pingone_application`:  Add Validation for disallowing Catalog Applications type

- .github/workflows/acceptance-test-ff-multi-region.yml
- .github/workflows/acceptance-test-multi-region.yml
- internal/service/base/data_source_license_test.go
- internal/service/base/resource_environment_test.go
- internal/service/sso/resource_population_test.go
Skipped tests will start failing June 14th, to remind us to remove the skip
Affects `TestAccEnvironment_EnvironmentTypeSwitching` and `TestAccPopulation_DataProtection`
> Temporarily skip tests that create prod environments

- .changelog/1065.txt
- internal/service/base/resource_phone_delivery_settings.go
- internal/service/base/resource_phone_delivery_settings_test.go
`pingone_phone_delivery_settings` resource bug fix: 
Resolve `UNIQUENESS_VIOLATION: A resource with the specified name already exists.` error when updating mutable attributes
N/A
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccPhoneDeliverySettings_Custom github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccPhoneDeliverySettings_Custom_Twilio
=== PAUSE TestAccPhoneDeliverySettings_Custom_Twilio
=== RUN   TestAccPhoneDeliverySettings_Custom_Syniverse
=== PAUSE TestAccPhoneDeliverySettings_Custom_Syniverse
=== RUN   TestAccPhoneDeliverySettings_Custom
=== PAUSE TestAccPhoneDeliverySettings_Custom
=== CONT  TestAccPhoneDeliverySettings_Custom_Twilio
=== CONT …
```
> `resource/pingone_phone_delivery_settings`: Fix update causes `UNIQUENESS_VIOLATION` error (#1065)

- .changelog/1073.txt
- internal/service/sso/resource_identity_provider_attribute.go
- internal/service/sso/resource_identity_provider_attribute_test.go
Fixed `Invalid parameter value - Unmappable identity provider type` error when deleting a `microsoft` identity provider attribute type.
N/A
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccIdentityProviderAttribute_MicrosoftIdentityProvider github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccIdentityProviderMicrosoftAttribute
=== PAUSE TestAccIdentityProviderMicrosoftAttribute
=== CONT  TestAccIdentityProviderMicrosoftAttribute
--- PASS: TestAccIdentityProviderMicrosoftAttribute (6.38s)
PASS
ok  	github.com/pingidentity/terraform-provider-pingone/internal/service/sso	6.946s
```
</details>
> `resource/pingone_identity_provider_attribute`: Fixed `Invalid parameter value` error

- .changelog/1080.txt
- internal/service/sso/data_source_population_test.go
- internal/service/sso/resource_population.go
- internal/service/sso/resource_population_default.go
- internal/service/sso/resource_population_gen.go
- internal/service/sso/resource_population_test.go
Fix `TestAccPopulationDataSource_ByNameFull` failing due to parallel tests enabling and disabling the preferred language simultaneously.
Fix `TestAccPopulation_NewEnv` by removing `theme.id` check that failed due to eventual consistency issues.
```
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccPopulation github.com/pingidentity/terraform-provider-pingone/internal/service/sso
=== RUN   TestAccPopulationDataSource_ByNameFull
=== PAUSE TestAccPopulationDataSource_ByNameFull
=== RUN   TestAccPopulationDataSource_ByIDFull
=== PAUSE TestAccPopulationDataSource_ByIDFull
=== RUN   TestAccPopulationDataSource_NotFound
=== PAUSE TestAccPopulationDataSource_NotFound
=== RUN   TestAccPopulationsDataSource_BySCIMFilter
=== PAUSE TestAccPopulationsDataSource_BySCIMFilter
=== RUN …
```
> Fix population test failures

- internal/service/base/resource_custom_domain_ssl_test.go
- internal/service/base/resource_custom_domain_verify_test.go
Use domain that aligns with test certificate, and randomize domain to avoid conflicts in pingone_custom_domain_verify test.
These were missed in #1082  because I mistakenly was using `-run ^TestAccCustomDomain_` (with underscore) instead of `-run ^TestAccCustomDomain` in my testing command.
Currently running a multi-region pipeline to confirm these fixes.
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccCustomDomain github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccCustomDomainSSL_Full
=== PAUSE TestAccCustomDomainSSL_Full
=== RUN   TestAccCustomDomain_RemovalDrift
=== PAUSE TestAccCustomDomain_RemovalDrift
=== RUN   TestAccCustomDomain_Full
=== PAUSE TestAccCustomDomain_Full
=== RUN …
```
> Custom domain test fixes

- .changelog/1089.txt
- docs/resources/population_default.md
- internal/service/sso/resource_population.go
- internal/service/sso/resource_population_default.go
- internal/service/sso/resource_population_default_test.go
Add new `theme`, `preferred_language`, and `alternative_identifiers` attributes to `pingone_population_default`. These attributes were added to `pingone_population` in #983.
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccPopulationDefault_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso -count=1
```
<details>
```shell
=== RUN   TestAccPopulationDefault_RemovalDrift
=== PAUSE TestAccPopulationDefault_RemovalDrift
=== RUN   TestAccPopulationDefault_Full
=== PAUSE TestAccPopulationDefault_Full
=== RUN   TestAccPopulationDefault_Minimal
=== PAUSE TestAccPopulationDefault_Minimal
=== RUN   TestAccPopulationDefault_BadParameters
=== PAUSE TestAccPopulationDefault_BadParameters
=== CONT  TestAccPopulationDefault_RemovalDrift
=== …
```
> Add new pingone_population attrs to pingone_population_default

- .changelog/1085.txt
- internal/service/base/resource_custom_domain_verify.go
Allow use of already verified custom domain
N/A
N/A
> `resource/custom_domain_verify`: Allow use of already verified custom domain

- .github/workflows/acceptance-test-ff-multi-region.yml
- .github/workflows/acceptance-test-multi-region.yml
Use matrix in acceptance test workflow with max-parallel to run tests sequentially for non-flaky pipelines. This should reduce any pressure caused by overlapping tests.
I have a run pending on a previous iteration where I was not yet using the matrix design: https://github.com/pingidentity/terraform-provider-pingone/actions/runs/16272451451
I am going to wait until that workflow is complete (so we don't trigger anything) to do a test run for this and confirm that the changes do not break anything. With max-parallel set to 1, it should behave similar to the PingFed provider scheduled tests.
> Sequential multi region tests

- .github/workflows/acceptance-test-ff-multi-region.yml
- .github/workflows/acceptance-test-ff-multi-version.yml
- .github/workflows/acceptance-test-multi-region.yml
- .github/workflows/acceptance-test-multi-version.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/gosec-scan.yml
Add back condition to only send failure webhook notifications when the failure was on a scheduled workflow.
> Add back schedule condition for failure webhook

- .github/workflows/acceptance-test-beta-multi-region.yml
- .github/workflows/acceptance-test-beta-multi-version.yml
Add needed variables for `TestAccApplicationDataSource_SAMLAppByID` test that is now running in beta test runs.
_All full (or complete) PRs that need review prior to merge should have the following box checked._
_If contributing a partial or incomplete change (expecting the development team to complete the remaining work) please leave the box unchecked_
- The changelog entry has been included according to the [changelog process](../contributing/changelog-process.md)
- Changes have proper test coverage (including regression tests)
- Impacted resource, data source and schema descriptions have been reviewed and updated
- Impacted resource and data source documentation HCL examples have been reviewed and updated
- Does not introduce breaking changes (unless required to do so)
- I am aware …
> Add vars for application data source beta test
