pingidentity/terraform-provider-pingone

.changelog/72.txt, GNUmakefile, internal/service/base/data_source_environment.go, internal/service/base/resource_environment.go, internal/service/base/resource_role_assignment_user.go, internal/service/sso/data_source_password_policy.go, internal/service/sso/data_source_schema.go, internal/service/sso/resource_application.go, internal/service/sso/resource_application_attribute_mapping.go, internal/service/sso/resource_application_resource_grant.go, internal/service/sso/resource_application_role_assignment.go, internal/service/sso/resource_application_sign_on_policy_assignment.go, internal/service/sso/resource_group.go, internal/service/sso/resource_password_policy.go, internal/service/sso/resource_population.go, internal/service/sso/resource_schema_attribute.go, internal/service/sso/resource_user.go
Adds a regexp validation to any schema attribute that represents a PingOne ID
=> add PingOne resource ID validation regexp

internal/service/base/data_source_certificate_export_test.go, internal/service/base/data_source_certificate_signing_request_test.go
Ref: #259 
Tests to be re-enabled on resolution
=> suppress failing key export tests

internal/service/sso/resource_application_test.go
```
TF_LOG= TF_LOG_PATH= TF_ACC=1 go test -v -timeout 240s -run ^TestAccApplication_SAML github.com/pingidentity/terraform-provider-pingone/internal/service/sso       
=== RUN   TestAccApplication_SAMLFull
=== PAUSE TestAccApplication_SAMLFull
=== RUN   TestAccApplication_SAMLMinimal
=== PAUSE TestAccApplication_SAMLMinimal
=== RUN   TestAccApplication_SAMLSigningKey
=== PAUSE TestAccApplication_SAMLSigningKey
=== CONT  TestAccApplication_SAMLFull
=== CONT  TestAccApplication_SAMLSigningKey
=== CONT  TestAccApplication_SAMLMinimal
--- PASS: TestAccApplication_SAMLMinimal (6.14s)
--- PASS: TestAccApplication_SAMLFull (7.46s)
--- PASS: TestAccApplication_SAMLSigningKey (37.24s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/sso 37.582s
```
=> Update SAML tests for new api behaviour

.changelog/378.txt, docs/resources/risk_predictor.md, examples/resources/pingone_risk_predictor/resource-custom.tf
* `resource/pingone_risk_predictor`: Corrected custom map type documentation example.
=> `resource/pingone_risk_predictor`: Corrected custom map type documentation example.

.changelog/387.txt, docs/resources/risk_predictor.md, examples/resources/pingone_risk_predictor/resource-anonymous-network.tf, examples/resources/pingone_risk_predictor/resource-composite.tf, examples/resources/pingone_risk_predictor/resource-custom.tf, examples/resources/pingone_risk_predictor/resource-geovelocity.tf, examples/resources/pingone_risk_predictor/resource-ip-reputation.tf, examples/resources/pingone_risk_predictor/resource-new-device.tf, examples/resources/pingone_risk_predictor/resource-user-location.tf, examples/resources/pingone_risk_predictor/resource-user-risk-behavior.tf, examples/resources/pingone_risk_predictor/resource-velocity.tf
* `resource/pingone_risk_predictor`: Corrected documentation examples.
N/a
=> `resource/pingone_risk_predictor`: Corrected documentation examples

internal/service/base/data_source_environment.go
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccEnvironmentDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccEnvironmentDataSource_ByNameFull
=== PAUSE TestAccEnvironmentDataSource_ByNameFull
=== RUN   TestAccEnvironmentDataSource_ByNameMinimal
=== PAUSE TestAccEnvironmentDataSource_ByNameMinimal
=== RUN   TestAccEnvironmentDataSource_ByIDFull
=== PAUSE TestAccEnvironmentDataSource_ByIDFull
=== RUN   TestAccEnvironmentDataSource_ByIDMinimal
=== PAUSE TestAccEnvironmentDataSource_ByIDMinimal
=== RUN   TestAccEnvironmentDataSource_NotFound
=== PAUSE TestAccEnvironmentDataSource_NotFound
=== CONT  TestAccEnvironmentDataSource_ByNameFull
=== CONT …
```
=> Fix environment DS code optimisation

internal/service/base/resource_certificate_signing_response_test.go
* Changed signed certificate import test check for validity period.  Platform responds correctly to expiry date differences between the key and signed certificate import
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccCertificateSigningResponse_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccCertificateSigningResponse_Full
=== PAUSE TestAccCertificateSigningResponse_Full
=== CONT  TestAccCertificateSigningResponse_Full
--- PASS: TestAccCertificateSigningResponse_Full (10.20s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        (cached)
```
=> Changed signed certificate import test check for validity period

.changelog/454.txt, docs/resources/mfa_fido_policy.md, docs/resources/mfa_policy.md, templates/resources/mfa_fido_policy.md.tmpl, templates/resources/mfa_policy.md.tmpl
* `resource/pingone_mfa_policy`: Corrected MFA policy upgrade guide link in registry documentation.
* `resource/pingone_mfa_fido_policy`: Corrected MFA policy upgrade guide link in registry documentation.
=> Correct MFA policy upgrade guide link in registry documentation

.changelog/455.txt, docs/guides/upgrade-mfa-policy-for-fido2.md, templates/guides/upgrade-mfa-policy-for-fido2.md
* Correct `Upgrade MFA Policies to use FIDO2 with Passkeys guide` text
=> Correct `Upgrade MFA Policies to use FIDO2 with Passkeys guide` text

.changelog/456.txt, docs/resources/application_resource_grant.md, internal/provider/sdkv2/provider.go, internal/service/sso/resource_application_resource_grant.go, internal/service/sso/service.go
* Migrate `pingone_application_resource_grant` to plugin framework
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccApplicationResourceGrant_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccApplicationResourceGrant_Change
=== PAUSE TestAccApplicationResourceGrant_Change
=== CONT  TestAccApplicationResourceGrant_OpenIDResource
=== CONT  TestAccApplicationResourceGrant_Change
=== CONT  TestAccApplicationResourceGrant_CustomResource
--- PASS: TestAccApplicationResourceGrant_OpenIDResource (8.04s)
--- PASS: …
```
=> Migrate `pingone_application_resource_grant` to plugin framework

internal/service/base/resource_notification_policy.go
* Fix `pingone_notification_policy` `country_limit` defaults issue
```shell
TF_LOG=DEBUG TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 360s -run ^TestAccNotificationPolicy_CountryLimit github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccNotificationPolicy_CountryLimit
=== PAUSE TestAccNotificationPolicy_CountryLimit
=== CONT  TestAccNotificationPolicy_CountryLimit
--- PASS: TestAccNotificationPolicy_CountryLimit (59.64s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        60.069s
```
=> Fix `pingone_notification_policy` `country_limit` defaults issue

.changelog/483.txt, go.mod, go.sum
```release-note:note
bump `github.com/patrickcping/pingone-go-sdk-v2` v0.10.0 => v0.10.1
```
```release-note:bug
Fixed provider parameter error "Invalid parameter format.  Expected URL with https scheme" when attempting to override service hostnames.
```
Deferred to nightly tests
=> bump `github.com/patrickcping/pingone-go-sdk-v2` v0.10.0 => v0.10.1

.changelog/487.txt, internal/service/sso/data_source_population.go, internal/service/sso/data_source_population_test.go
* Optimise `pingone_population` data source selection by name filter
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 360s -run ^TestAccPopulationDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccPopulationDataSource_ByNameFull
=== PAUSE TestAccPopulationDataSource_ByNameFull
=== RUN   TestAccPopulationDataSource_ByIDFull
=== PAUSE TestAccPopulationDataSource_ByIDFull
=== RUN   TestAccPopulationDataSource_NotFound
=== PAUSE TestAccPopulationDataSource_NotFound
=== CONT  TestAccPopulationDataSource_ByNameFull
=== CONT  TestAccPopulationDataSource_NotFound
=== CONT  TestAccPopulationDataSource_ByIDFull
--- PASS: TestAccPopulationDataSource_NotFound (3.86s)
--- PASS: …
```
=> Optimise `pingone_population` data source selection by name filter

.changelog/498.txt, internal/provider/framework/provider.go
* Correct service parameter dereferencing bug
=> Correct service parameter dereferencing

.changelog/508.txt, docs/resources/trusted_email_domain.md, internal/provider/sdkv2/provider.go, internal/service/base/resource_trusted_email_domain.go, internal/service/base/service.go
* `resource/pingone_trusted_email_domain`: Migrated to plugin framework
```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 500s -run ^TestAccTrustedEmailDomain_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccTrustedEmailDomain_RemovalDrift
=== PAUSE TestAccTrustedEmailDomain_RemovalDrift
=== RUN   TestAccTrustedEmailDomain_Full
=== PAUSE TestAccTrustedEmailDomain_Full
=== CONT  TestAccTrustedEmailDomain_RemovalDrift
=== CONT  TestAccTrustedEmailDomain_Full
--- PASS: TestAccTrustedEmailDomain_Full (9.08s)
--- PASS: TestAccTrustedEmailDomain_RemovalDrift (11.04s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        11.733s
```
=> `resource/pingone_trusted_email_domain`: Migrated to plugin framework

docs/resources/custom_domain_ssl.md, internal/service/base/resource_custom_domain_ssl.go
* Adjust custom domain SSL replace plan descriptions
N/a
=> Adjust custom domain SSL replace plan descriptions

docs/index.md, templates/index.md.tmpl
- Add links to developer experience examples and resources on the documentation index
N/a
=> Add links to developer experience examples and resources

.changelog/572.txt, docs/resources/certificate.md, examples/resources/pingone_certificate/resource-pem.tf, internal/service/base/resource_certificate.go
- `resource/pingone_certificate`: Adjusted documentation for PEM certificate import
N/a
=> `resource/pingone_certificate`: Adjusted documentation for PEM certificate import

.changelog/575.txt, docs/resources/key.md, internal/provider/sdkv2/provider.go, internal/service/base/resource_key.go, internal/service/base/resource_key_test.go, internal/service/base/service.go
- `resource/pingone_key`: Migrated to plugin framework.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccKey_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
```shell
=== RUN   TestAccKey_RemovalDrift
=== PAUSE TestAccKey_RemovalDrift
=== RUN   TestAccKey_Full
=== PAUSE TestAccKey_Full
=== RUN   TestAccKey_Minimal
=== PAUSE TestAccKey_Minimal
=== RUN   TestAccKey_PKCS12
=== PAUSE TestAccKey_PKCS12
=== RUN   TestAccKey_Change
=== PAUSE TestAccKey_Change
=== RUN   TestAccKey_CustomCRL
=== PAUSE TestAccKey_CustomCRL
=== RUN   TestAccKey_BadParameters
=== PAUSE TestAccKey_BadParameters
=== CONT  TestAccKey_RemovalDrift
=== CONT  TestAccKey_Change
=== CONT  TestAccKey_CustomCRL
=== CONT  TestAccKey_Full
=== CONT  TestAccKey_Minimal
=== CONT …
```
=> `resource/pingone_key`: Migrated to plugin framework.

internal/service/mfa/resource_mfa_settings.go, internal/service/sso/resource_schema_attribute.go
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccMFASettings_RemovalDrift github.com/pingidentity/terraform-provider-pingone/internal/service/mfa && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccSchemaAttribute_RemovalDrift github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccMFASettings_RemovalDrift
=== PAUSE TestAccMFASettings_RemovalDrift
=== CONT  TestAccMFASettings_RemovalDrift
--- PASS: TestAccMFASettings_RemovalDrift (12.75s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/mfa 13.753s
=== RUN   TestAccSchemaAttribute_RemovalDrift
=== PAUSE TestAccSchemaAttribute_RemovalDrift
=== CONT  TestAccSchemaAttribute_RemovalDrift
--- PASS: TestAccSchemaAttribute_RemovalDrift (14.17s)
PASS
ok …
```
=> Environment removal drift handling

internal/service/base/data_source_certificate_export_test.go, internal/service/base/data_source_certificate_signing_request_test.go, internal/service/base/data_source_certificate_test.go, internal/service/base/data_source_organization_test.go, internal/service/base/data_source_trusted_email_domain_test.go, internal/service/base/resource_certificate_signing_response_test.go, internal/service/base/resource_certificate_test.go, internal/service/base/resource_custom_domain_ssl_test.go, internal/service/base/resource_image_test.go, internal/service/base/resource_key_rotation_policy_test.go, internal/service/base/resource_key_test.go, internal/service/base/resource_phone_delivery_settings_test.go, internal/service/base/resource_role_assignment_user_test.go, internal/service/base/resource_trusted_email_address_test.go, internal/service/mfa/resource_application_push_credential_test.go, internal/service/mfa/resource_mfa_policy_test.go, internal/service/sso/resource_application_test.go, internal/service/sso/resource_sign_on_policy_action_test.go
- Add back skips/checks for tests with "no feature flag" requirement, as without them it causes failures on tests with feature flag requirements
=> Add back the missing "no feature flag" test skips

internal/framework/sdk.go
- Fix panic on non-http errors.  No changelog required as impacted code not yet released
=> Fix panic on non-http errors

.changelog/593.txt, docs/data-sources/digital_wallet_applications.md, docs/data-sources/trusted_email_domain.md, internal/framework/resource.go, internal/service/base/data_source_environments.go, internal/service/base/data_source_organization.go, internal/service/base/data_source_phone_delivery_settings_list.go, internal/service/base/data_source_trusted_email_domain.go, internal/service/base/resource_notification_policy.go, internal/service/base/resource_trusted_email_address.go, internal/service/credentials/data_source_credential_types.go, internal/service/credentials/data_source_digital_wallet_applications.go, internal/service/mfa/data_source_mfa_policies.go, internal/service/risk/resource_risk_policy.go, internal/service/risk/resource_risk_predictor.go, internal/service/sso/data_source_flow_policies.go, internal/service/sso/data_source_populations.go, internal/service/sso/data_source_users.go, internal/service/verify/data_source_verify_policies.go, internal/service/verify/data_source_verify_voice_phrase_contents.go, internal/service/verify/resource_verify_policy.go
- Align schema documentation code standards
- Align state persistence data type conversion
- `data-source/pingone_trusted_email_domain`: Corrected documentation descriptions.
=> Align code to standards

.changelog/635.txt, internal/service/sso/resource_group_role_assignment.go
- `resource/pingone_group_role_assignment`: Added error check if a read-only role assignment is being destroyed.
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccRoleAssignmentGroup_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
```shell
=== RUN   TestAccRoleAssignmentGroup_RemovalDrift
=== PAUSE TestAccRoleAssignmentGroup_RemovalDrift
=== RUN   TestAccRoleAssignmentGroup_Population
=== PAUSE TestAccRoleAssignmentGroup_Population
=== RUN   TestAccRoleAssignmentGroup_Organisation
=== PAUSE TestAccRoleAssignmentGroup_Organisation
=== RUN   TestAccRoleAssignmentGroup_Environment
=== PAUSE TestAccRoleAssignmentGroup_Environment
=== RUN   TestAccRoleAssignmentGroup_BadParameters
=== PAUSE TestAccRoleAssignmentGroup_BadParameters
=== CONT …
```
=> `resource/pingone_group_role_assignment`: Added error check if a read-only role assignment is being destroyed

.changelog/648.txt, docs/resources/population_default.md, templates/resources/population_default.md.tmpl
- `resource/pingone_population_default`: Corrected documentation notes.
N/a
=> `resource/pingone_population_default`: Correct documentation notes

.changelog/657.txt, docs/guides/version-1-upgrade.md, templates/guides/version-1-upgrade.md
- Update application resource grant upgrade doc text
N/a
N/a
N/a
=> Update application resource grant upgrade doc text

.changelog/661.txt, docs/guides/version-1-upgrade.md, docs/resources/branding_settings.md, docs/resources/branding_theme.md, docs/resources/credential_type.md, docs/resources/identity_provider.md, examples/resources/pingone_branding_settings/resource.tf, examples/resources/pingone_branding_theme/resource.tf, examples/resources/pingone_credential_type/resource.tf, internal/service/base/resource_branding_settings.go, internal/service/base/resource_branding_settings_test.go, internal/service/base/resource_branding_theme.go, internal/service/base/resource_branding_theme_test.go, internal/service/credentials/resource_credential_type.go, internal/service/credentials/resource_credential_type_test.go, internal/service/sso/resource_identity_provider.go, internal/service/sso/resource_identity_provider_test.go, internal/service/utils_image.go, templates/guides/version-1-upgrade.md
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccBrandingSettings_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccBrandingTheme_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccIdentityProvider_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccBrandingSettings_RemovalDrift
=== PAUSE TestAccBrandingSettings_RemovalDrift
=== RUN   TestAccBrandingSettings_Full
=== PAUSE TestAccBrandingSettings_Full
=== RUN   TestAccBrandingSettings_Minimal1
=== PAUSE TestAccBrandingSettings_Minimal1
=== RUN   TestAccBrandingSettings_Minimal2
=== …
```
=> Change image logo data types (`v1.0.0`)

.changelog/664.txt, docs/data-sources/flow_policies.md, docs/data-sources/populations.md, docs/data-sources/users.md, docs/guides/version-1-upgrade.md, examples/data-sources/pingone_flow_policies/data-source.tf, examples/data-sources/pingone_populations/data-source.tf, examples/data-sources/pingone_users/data-source.tf, internal/framework/schema_common.go, internal/service/sso/data_source_flow_policies.go, internal/service/sso/data_source_flow_policies_test.go, internal/service/sso/data_source_populations.go, internal/service/sso/data_source_populations_test.go, internal/service/sso/data_source_users.go, internal/service/sso/data_source_users_test.go, templates/guides/version-1-upgrade.md
- `data-source/pingone_flow_policies`: Changed the `data_filter` parameter data type and renamed to `data_filters`.
- `data-source/pingone_populations`: Changed the `data_filter` parameter data type and renamed to `data_filters`.
- `data-source/pingone_users`: Changed the `data_filter` parameter data type and renamed to `data_filters`.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccFlowPoliciesDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccPopulationsDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso && \
TF_ACC=1 go test -v -timeout 500s -run ^TestAccUsersDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details> …
=> Change the `data_filter` block parameter data type and rename

.changelog/665.txt, docs/data-sources/environment.md, docs/guides/version-1-upgrade.md, docs/resources/environment.md, examples/resources/pingone_environment/resource.tf, internal/acctest/acctest.go, internal/service/base/data_source_environment.go, internal/service/base/data_source_environment_test.go, internal/service/base/data_source_environments_test.go, internal/service/base/resource_environment.go, internal/service/base/resource_environment_test.go, internal/service/credentials/data_source_credential_issuer_profile_test.go, templates/guides/version-1-upgrade.md
- `data-source/pingone_environment`: Changed the `service` parameter data type and renamed to `services`.
- `data-source/pingone_environment`: Changed the `service.bookmark` parameter data type and renamed to `services.bookmarks`.
- `resource/pingone_environment`: Changed the `service` parameter data type, renamed to `services` and made a required parameter.
- `resource/pingone_environment`: Moved `service.type` to `services.type` and made a required parameter.
- `resource/pingone_environment`: Changed the `service.bookmark` parameter data type and renamed to `services.bookmarks`.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccEnvironment_ github.com/pingidentity/terraform-provider-pingone/internal/service/base && \
TF_ACC=1 go test -v -timeout 500s -run …
```
=> Change environment block parameters

.changelog/669.txt, docs/resources/user.md, examples/resources/pingone_user/resource.tf
- Correct `pingone_user` HCL example
N/a
N/a
N/a
=> Correct `pingone_user` HCL example

.changelog/670.txt, docs/data-sources/population.md, docs/resources/population.md, internal/service/sso/data_source_population.go, internal/service/sso/resource_population.go
- `resource/pingone_population`: Update schema documentation.
- `data-source/pingone_population`: Update schema documentation.
N/a
N/a
N/a
=> Update `pingone_population` schema documentation

internal/service/sso/resource_user.go
`resource/pingone_user`: Add retry for observed race condition (changelog not necessary)
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccUser_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccUser_RemovalDrift
=== PAUSE TestAccUser_RemovalDrift
=== RUN   TestAccUser_NewEnv
=== PAUSE TestAccUser_NewEnv
=== RUN   TestAccUser_All
=== PAUSE TestAccUser_All
=== RUN   TestAccUser_AllWithoutReplacement
=== PAUSE TestAccUser_AllWithoutReplacement
=== RUN   TestAccUser_AccountLocked
=== PAUSE TestAccUser_AccountLocked
=== RUN   TestAccUser_ChangePopulation
=== PAUSE TestAccUser_ChangePopulation
=== RUN   TestAccUser_ChangeMFA
=== PAUSE TestAccUser_ChangeMFA
=== RUN …
```
=> `resource/pingone_user`: Add retry for observed race condition

.changelog/684.txt, docs/resources/application_attribute_mapping.md, examples/resources/pingone_application_attribute_mapping/resource-oidc-custom-resource-scope.tf, templates/resources/application_attribute_mapping.md.tmpl
- `resource/pingone_application_attribute_mapping`: Corrected application attribute mapping example when using custom OIDC scopes.
N/a
N/a
=> Fix application attribute mapping example

.changelog/687.txt, internal/verify/validate.go, internal/verify/validate_test.go
- Fix HTTP/HTTPS URL validation regex (multiple resources)
- Resolved validation on:
- `pingone_branding_settings.logo_image.href`
- `pingone_branding_theme.logo.href`
- `pingone_branding_theme.background_image.href`
- `pingone_phone_delivery_settings.provider_custom.requests.url`
- `pingone_credential_type.metadata.background_image`
- `pingone_credential_type.metadata.logo_image`
- `pingone_identity_provider.login_button_icon.href`
- `pingone_identity_provider.icon.href`
- `pingone_identity_provider.openid_connect.authorization_endpoint`
- `pingone_identity_provider.openid_connect.discovery_endpoint`
- `pingone_identity_provider.openid_connect.issuer`
- `pingone_identity_provider.openid_connect.jwks_endpoint`
- `pingone_identity_provider.openid_connect.token_endpoint`
- …
=> Fix HTTP/HTTPS URL validation regex

.changelog/691.txt, docs/resources/application_role_assignment.md, docs/resources/gateway.md, docs/resources/gateway_role_assignment.md, docs/resources/group.md, docs/resources/group_nesting.md, docs/resources/group_role_assignment.md, docs/resources/population.md, docs/resources/role_assignment_user.md, docs/resources/schema_attribute.md, docs/resources/user.md, docs/resources/user_group_assignment.md, examples/resources/pingone_application_role_assignment/resource-population.tf, examples/resources/pingone_gateway/resource-ldap.tf, examples/resources/pingone_gateway_role_assignment/resource-population.tf, examples/resources/pingone_group/resource.tf, examples/resources/pingone_group_nesting/resource.tf, examples/resources/pingone_group_role_assignment/resource-environment.tf, examples/resources/pingone_group_role_assignment/resource-organization.tf, examples/resources/pingone_group_role_assignment/resource-population.tf, examples/resources/pingone_population/resource.tf, examples/resources/pingone_role_assignment_user/resource-population.tf, examples/resources/pingone_schema_attribute/resource-with-regex-validation.tf, examples/resources/pingone_schema_attribute/resource.tf, examples/resources/pingone_user/resource.tf, examples/resources/pingone_user_group_assignment/resource.tf, templates/resources/group.md.tmpl, templates/resources/population.md.tmpl, templates/resources/schema_attribute.md.tmpl
- Add `lifecycle.prevent_destroy` best practice to data-carrying resource's documentation
N/a
N/a
=> Add `lifecycle.prevent_destroy` best practice to data-carrying resource's documentation

internal/service/risk/resource_risk_predictor_test.go, internal/service/sso/resource_sign_on_policy_action_test.go
- Adjust tests based on import test failures found following #689
=> Import test failure triage

.github/workflows/code-check.yml, .github/workflows/unit-test.yml
Update actions to reduce duplicated runs
=> update actions to reduce unnecessary action runs

.changelog/714.txt, internal/service/base/resource_form.go, internal/service/base/resource_form_test.go
* `resource/pingone_form`: Fix error "This attribute contains duplicate values of the same type" when configuring multiple form controls of the same type.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccForm_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccForm_RemovalDrift
=== PAUSE TestAccForm_RemovalDrift
=== RUN   TestAccForm_NewEnv
=== PAUSE TestAccForm_NewEnv
=== RUN   TestAccForm_Full
=== PAUSE TestAccForm_Full
=== RUN   TestAccForm_Multiple
=== PAUSE TestAccForm_Multiple
=== RUN   TestAccForm_FieldCheckbox
=== PAUSE TestAccForm_FieldCheckbox
=== RUN   TestAccForm_FieldCombobox
=== PAUSE TestAccForm_FieldCombobox
=== RUN   TestAccForm_FieldDropdown
=== PAUSE …
```
=> `resource/pingone_form`: Fix error "This attribute contains duplicate values of the same type"

.changelog/722.txt, docs/resources/notification_policy.md, examples/resources/pingone_notification_policy/resource-environment.tf, examples/resources/pingone_notification_policy/resource-unlimited.tf, examples/resources/pingone_notification_policy/resource-user.tf, internal/service/base/resource_notification_policy.go, internal/service/base/resource_notification_policy_test.go
- `resource/pingone_notification_policy`: Support `Email` delivery method quotas.
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccNotificationPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationPolicy_RemovalDrift
=== PAUSE TestAccNotificationPolicy_RemovalDrift
=== RUN   TestAccNotificationPolicy_NewEnv
=== PAUSE TestAccNotificationPolicy_NewEnv
=== RUN   TestAccNotificationPolicy_Full
=== PAUSE TestAccNotificationPolicy_Full
=== RUN   TestAccNotificationPolicy_Quotas
=== PAUSE TestAccNotificationPolicy_Quotas
=== RUN   TestAccNotificationPolicy_CountryLimit
=== PAUSE TestAccNotificationPolicy_CountryLimit
=== RUN   TestAccNotificationPolicy_BadParameters
=== …
```
=> `resource/pingone_notification_policy`: Support `Email` delivery method quotas

.changelog/730.txt, docs/data-sources/licenses.md, docs/guides/version-1-upgrade.md, examples/data-sources/pingone_licenses/data-source.tf, internal/service/base/data_source_licenses.go, internal/service/base/data_source_licenses_test.go, templates/guides/version-1-upgrade.md
- `data-source/pingone_licenses`: Change the data filter type and rename
- 
N/a
```shell
TF_ACC=1 go test -v -timeout 500s -run ^TestAccLicensesDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccLicensesDataSource_BySCIMFilter
=== PAUSE TestAccLicensesDataSource_BySCIMFilter
=== RUN   TestAccLicensesDataSource_ByDataFilter
=== PAUSE TestAccLicensesDataSource_ByDataFilter
=== RUN   TestAccLicensesDataSource_NotFound
=== PAUSE TestAccLicensesDataSource_NotFound
=== CONT  TestAccLicensesDataSource_BySCIMFilter
=== CONT  TestAccLicensesDataSource_NotFound
=== CONT  TestAccLicensesDataSource_ByDataFilter
--- PASS: TestAccLicensesDataSource_NotFound (3.31s)
--- PASS: …
```
=> `data-source/pingone_licenses`: Change the data filter type and rename

.github/workflows/acceptance-test-multi-region.yml, .github/workflows/acceptance-test-multi-version.yml, internal/acctest/acctest.go, internal/service/base/resource_phone_delivery_settings_test.go, internal/service/base/resource_trusted_email_address_test.go
- Add acctest skip for environments with unverified email domains
Changelog not needed
N/a
Deferred to nightly tests
=> Add acctest skip for environments with unverified email domains

.changelog/789.txt, docs/guides/version-1-upgrade.md, docs/resources/notification_policy.md, examples/resources/pingone_notification_policy/resource-environment.tf, examples/resources/pingone_notification_policy/resource-user.tf, internal/service/base/resource_notification_policy.go, internal/service/base/resource_notification_policy_test.go, templates/guides/version-1-upgrade.md
- `resource/pingone_notification_policy`: Change the `quota` data type
N/a
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccNotificationPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationPolicy_RemovalDrift
=== PAUSE TestAccNotificationPolicy_RemovalDrift
=== RUN   TestAccNotificationPolicy_NewEnv
=== PAUSE TestAccNotificationPolicy_NewEnv
=== RUN   TestAccNotificationPolicy_Full
=== PAUSE TestAccNotificationPolicy_Full
=== RUN   TestAccNotificationPolicy_Quotas
=== PAUSE TestAccNotificationPolicy_Quotas
=== RUN   TestAccNotificationPolicy_CountryLimit
=== PAUSE TestAccNotificationPolicy_CountryLimit
=== RUN   TestAccNotificationPolicy_BadParameters
=== PAUSE …
```
=> `resource/pingone_notification_policy`: Change the `quota` data type

.changelog/821.txt, examples/resources/pingone_authorize_application_role_permission/import.sh, examples/resources/pingone_authorize_application_role_permission/resource.tf, internal/acctest/service/authorize/application_role_permission.go, internal/service/authorize/resource_application_role_permission.go, internal/service/authorize/resource_application_role_permission_test.go, templates/resources/authorize_application_role_permission.md.tmpl
- draft `pingone_authorize_application_role_permission` resource
- `github.com/patrickcping/pingone-go-sdk-v2/authorize` `v0.5.0`
Deferred to aggregated PR
=> draft `pingone_authorize_application_role_permission` resource

.changelog/859.txt, internal/service/sso/resource_resource_attribute.go
- **Bug**: `resource/pingone_resource_attribute`: Remove restrictive validation preventing config generation of default OIDC attributes
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccResourceAttribute_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccResourceAttribute_RemovalDrift
=== PAUSE TestAccResourceAttribute_RemovalDrift
=== RUN   TestAccResourceAttribute_OIDC_Custom
=== PAUSE TestAccResourceAttribute_OIDC_Custom
=== RUN   TestAccResourceAttribute_OIDC_ReservedAttributeName
=== PAUSE TestAccResourceAttribute_OIDC_ReservedAttributeName
=== RUN   TestAccResourceAttribute_OIDC_Predefined
=== PAUSE TestAccResourceAttribute_OIDC_Predefined
=== RUN …
```
=> `resource/pingone_resource_attribute`: Remove restrictive validation preventing config generation of default OIDC attributes

internal/service/base/resource_image.go, internal/service/base/resource_image_schema_upgrade_0_to_1.go, internal/service/sso/resource_application_schema_upgrade_0_to_1.go
- `resource/pingone_image` v0 to v1 state upgrader
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccImage_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccImage_RemovalDrift
=== PAUSE TestAccImage_RemovalDrift
=== RUN   TestAccImage_PNG
=== PAUSE TestAccImage_PNG
=== RUN   TestAccImage_JPG
=== PAUSE TestAccImage_JPG
=== RUN   TestAccImage_GIF
=== PAUSE TestAccImage_GIF
=== RUN   TestAccImage_BadParameters
=== PAUSE TestAccImage_BadParameters
=== CONT  TestAccImage_RemovalDrift
=== CONT  TestAccImage_GIF
=== CONT  TestAccImage_JPG
=== CONT  TestAccImage_PNG
=== CONT  TestAccImage_BadParameters
--- PASS: TestAccImage_GIF (7.53s)
--- PASS: TestAccImage_JPG (7.93s)
--- PASS: …
```
=> `resource/pingone_image` v0 to v1 state upgrader

internal/service/base/resource_branding_theme.go, internal/service/base/resource_branding_theme_schema_upgrade_0_to_1.go, internal/service/sso/resource_application_schema_upgrade_0_to_1.go, internal/service/utils_image.go
- `resource/pingone_branding_theme` v0 to v1 state upgrader
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccBrandingTheme_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccBrandingTheme_RemovalDrift
=== PAUSE TestAccBrandingTheme_RemovalDrift
=== RUN   TestAccBrandingTheme_NewEnv
=== PAUSE TestAccBrandingTheme_NewEnv
=== RUN   TestAccBrandingTheme_Full
=== PAUSE TestAccBrandingTheme_Full
=== RUN   TestAccBrandingTheme_Minimal
=== PAUSE TestAccBrandingTheme_Minimal
=== RUN   TestAccBrandingTheme_Change
=== PAUSE TestAccBrandingTheme_Change
=== RUN   TestAccBrandingTheme_BadParameters
=== PAUSE TestAccBrandingTheme_BadParameters
=== CONT  TestAccBrandingTheme_RemovalDrift
=== CONT …
```
=> `resource/pingone_branding_theme` v0 to v1 state upgrader

docs/guides/version-1-upgrade.md, internal/service/base/data_source_gateway.go, internal/service/base/resource_gateway.go, internal/service/base/resource_gateway_schema_upgrade_0_to_1.go, templates/guides/version-1-upgrade.md
- `resource/pingone_gateway` state upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccGateway_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccGateway_RemovalDrift
=== PAUSE TestAccGateway_RemovalDrift
=== RUN   TestAccGateway_NewEnv
=== PAUSE TestAccGateway_NewEnv
=== RUN   TestAccGateway_Full
=== PAUSE TestAccGateway_Full
=== RUN   TestAccGateway_Minimal
=== PAUSE TestAccGateway_Minimal
=== RUN   TestAccGateway_Change
=== PAUSE TestAccGateway_Change
=== RUN   TestAccGateway_PF
=== PAUSE TestAccGateway_PF
=== RUN   TestAccGateway_APIG
=== PAUSE TestAccGateway_APIG
=== RUN   TestAccGateway_Intelligence
=== PAUSE TestAccGateway_Intelligence
=== RUN …
```
=> `resource/pingone_gateway` state upgrader v0 to v1

internal/service/sso/resource_identity_provider.go, internal/service/sso/resource_identity_provider_schema_upgrade_0_to_1.go
- `resource/pingone_identity_provider` state upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccIdentityProvider_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccIdentityProvider_RemovalDrift
=== PAUSE TestAccIdentityProvider_RemovalDrift
=== RUN   TestAccIdentityProvider_NewEnv
=== PAUSE TestAccIdentityProvider_NewEnv
=== RUN   TestAccIdentityProvider_Change
=== PAUSE TestAccIdentityProvider_Change
=== RUN   TestAccIdentityProvider_Facebook
=== PAUSE TestAccIdentityProvider_Facebook
=== RUN   TestAccIdentityProvider_Google
=== PAUSE TestAccIdentityProvider_Google
=== RUN   TestAccIdentityProvider_LinkedIn
=== PAUSE TestAccIdentityProvider_LinkedIn
=== RUN …
```
=> `resource/pingone_identity_provider` state upgrader v0 to v1

docs/guides/version-1-upgrade.md, internal/service/sso/resource_password_policy.go, internal/service/sso/resource_password_policy_schema_upgrade_0_to_1.go, templates/guides/version-1-upgrade.md
- `resource/pingone_password_policy` state upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccPasswordPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/sso
```
<details>
```shell
=== RUN   TestAccPasswordPolicy_RemovalDrift
=== PAUSE TestAccPasswordPolicy_RemovalDrift
=== RUN   TestAccPasswordPolicy_NewEnv
=== PAUSE TestAccPasswordPolicy_NewEnv
=== RUN   TestAccPasswordPolicy_Full
=== PAUSE TestAccPasswordPolicy_Full
=== RUN   TestAccPasswordPolicy_Minimal
=== PAUSE TestAccPasswordPolicy_Minimal
=== RUN   TestAccPasswordPolicy_BadParameters
=== PAUSE TestAccPasswordPolicy_BadParameters
=== CONT  TestAccPasswordPolicy_RemovalDrift
=== CONT  TestAccPasswordPolicy_Minimal
=== CONT …
```
=> `resource/pingone_password_policy` state upgrader v0 to v1

internal/service/base/resource_webhook.go, internal/service/base/resource_webhook_schema_upgrade_0_to_1.go
- `resource/pingone_webhook` schema upgrader v0 to v1
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccWebhook_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccWebhook_RemovalDrift
=== PAUSE TestAccWebhook_RemovalDrift
=== RUN   TestAccWebhook_NewEnv
=== PAUSE TestAccWebhook_NewEnv
=== RUN   TestAccWebhook_Full
=== PAUSE TestAccWebhook_Full
=== RUN   TestAccWebhook_Minimal
=== PAUSE TestAccWebhook_Minimal
=== RUN   TestAccWebhook_Change
=== PAUSE TestAccWebhook_Change
=== RUN   TestAccWebhook_MTLS
=== PAUSE TestAccWebhook_MTLS
=== RUN   TestAccWebhook_Applications
=== PAUSE TestAccWebhook_Applications
=== RUN   TestAccWebhook_Populations
=== PAUSE TestAccWebhook_Populations
=== …
```
=> `resource/pingone_webhook` schema upgrader v0 to v1

internal/service/base/resource_key_rotation_policy.go
- Add wait for KRP delete to fix testing errors
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccKeyRotationPolicy_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccKeyRotationPolicy_RemovalDrift
=== PAUSE TestAccKeyRotationPolicy_RemovalDrift
=== RUN   TestAccKeyRotationPolicy_NewEnv
=== PAUSE TestAccKeyRotationPolicy_NewEnv
=== RUN   TestAccKeyRotationPolicy_All
=== PAUSE TestAccKeyRotationPolicy_All
=== RUN   TestAccKeyRotationPolicy_BadParameters
=== PAUSE TestAccKeyRotationPolicy_BadParameters
=== CONT  TestAccKeyRotationPolicy_RemovalDrift
=== CONT  TestAccKeyRotationPolicy_All
=== CONT  TestAccKeyRotationPolicy_NewEnv
=== CONT  TestAccKeyRotationPolicy_BadParameters
--- …
```
=> Add wait for KRP delete to fix testing errors

contributing/provider-design.md, internal/sdk/retry.go, internal/service/base/resource_environment.go, internal/service/base/resource_key.go, internal/service/base/resource_notification_template_content_test.go, internal/service/credentials/data_source_credential_issuer_profile.go, internal/service/credentials/resource_credential_issuer_profile.go, internal/service/credentials/resource_credential_type.go, internal/service/sso/resource_population.go, internal/service/sso/resource_resource_scope_openid.go, internal/service/sso/resource_resource_scope_pingone_api.go, internal/service/utils_role_assignment.go
- Fix impossile condition lint issues
- 
N/a
Deferred to nightly
=> Fix impossile condition lint issues

internal/service/sso/data_source_resource_scope.go, internal/service/sso/resource_application_attribute_mapping_test.go, internal/service/sso/resource_application_resource_grant.go, internal/service/sso/resource_resource_scope_openid.go, internal/service/sso/resource_resource_scope_pingone_api.go
- Correct resource scope test errors from v1 update
- Changelog not needed
N/a
Deferred to GH actions
=> Correct resource scope test errors from v1 update

internal/service/base/resource_agreement_localization_revision.go
- `resource/pingone_agreement_localization_revision`: Add wait when revision effective date is implicitly calculated
N/a
```shell
TF_ACC=1 go test -v -timeout 1200s -run ^TestAccAgreementLocalizationRevision_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccAgreementLocalizationRevision_RemovalDrift
=== PAUSE TestAccAgreementLocalizationRevision_RemovalDrift
=== RUN   TestAccAgreementLocalizationRevision_Full
=== PAUSE TestAccAgreementLocalizationRevision_Full
=== RUN   TestAccAgreementLocalizationRevision_BadParameters
=== PAUSE TestAccAgreementLocalizationRevision_BadParameters
=== CONT  TestAccAgreementLocalizationRevision_RemovalDrift
=== CONT …
```
=> `resource/pingone_agreement_localization_revision`: Add wait when revision effective date is implicitly calculated

docs/guides/admin-role-management.md, templates/guides/admin-role-management.md.tmpl
- Correction to admin role guide
N/a
N/a
=> Correction to admin role guide

internal/framework/resource.go, internal/service/authorize/resource_api_service.go, internal/service/authorize/resource_api_service_operation.go, internal/service/base/data_source_licenses.go, internal/service/base/resource_alert_channel.go, internal/service/base/resource_environment.go, internal/service/base/resource_form.go, internal/service/base/resource_gateway.go, internal/service/base/resource_key.go, internal/service/base/resource_notification_policy.go, internal/service/base/resource_notification_settings.go, internal/service/base/resource_phone_delivery_settings.go, internal/service/base/resource_system_application.go, internal/service/base/resource_webhook.go, internal/service/credentials/resource_credential_issuance_rule.go, internal/service/credentials/resource_credential_type.go, internal/service/mfa/resource_fido2_policy.go, internal/service/risk/resource_risk_policy.go, internal/service/sso/resource_application.go, internal/service/sso/resource_application_resource_grant.go, internal/service/sso/resource_identity_provider.go, internal/service/sso/resource_identity_provider_schema_upgrade_0_to_1.go, internal/service/sso/resource_resource_scope_openid.go, internal/service/sso/resource_resource_scope_pingone_api.go, internal/service/sso/resource_schema_attribute.go
- Fix errors on `terraform validate` with unknown values
- Changelog update not needed
N/a
Deferred to nightly actions
=> Fix errors on `terraform validate` with unknown values

internal/framework/sdk.go, internal/service/base/resource_agreement_enable.go, internal/service/base/resource_agreement_localization.go, internal/service/base/resource_agreement_localization_revision.go, internal/service/base/resource_custom_domain_ssl.go, internal/service/base/resource_custom_domain_verify.go, internal/service/base/resource_environment.go, internal/service/base/resource_gateway.go, internal/service/base/resource_notification_policy.go, internal/service/base/resource_notification_template_content.go, internal/service/base/resource_phone_delivery_settings.go, internal/service/base/resource_trusted_email_address.go, internal/service/mfa/resource_fido2_policy.go, internal/service/mfa/resource_mfa_device_policy.go, internal/service/risk/resource_risk_policy.go, internal/service/risk/resource_risk_predictor.go, internal/service/sso/resource_application.go, internal/service/sso/resource_password_policy.go, internal/service/sso/resource_population.go, internal/service/sso/resource_sign_on_policy.go, internal/service/utils_role_assignment.go, internal/service/verify/resource_verify_policy.go
- Enhance custom error handling to include http response
- Changelog not needed
N/a
Deferred to nightly
=> Enhance custom error handling to include http response

.changelog/907.txt, docs/resources/environment.md, examples/resources/pingone_environment/resource.tf
`resource/pingone_environment`: Align example HCL with best practice on creating blank/empty DaVinci service environments
N/a
N/a
=> `resource/pingone_environment`: Align example HCL with best practice on creating blank/empty DaVinci service environments

.github/workflows/acceptance-test-ff-multi-region.yml, .github/workflows/acceptance-test-ff-multi-version.yml
=> Disable DV tests 2025-01

LICENSE
Converted from Mozilla license to Apache 2.0 License as per conversations with legal
No other changes made to any files as part of this PR, just the single file
=> convert to Apache 2.0 license

.changelog/1022.txt, docs/resources/sign_on_policy.md, docs/resources/sign_on_policy_action.md, examples/resources/pingone_sign_on_policy/resource.tf, examples/resources/pingone_sign_on_policy_action/resource-mfa.tf
- Updating docs to use the correct field for MFA sign on policy actions
N/a (docs change)
N/a (docs change)
=> Correct MFA SOP action example in documentation

.github/workflows/acceptance-test-ff-multi-region.yml
Fix workflow syntax for nightly feature flagged tests
=> Fix needs in multi region workflow onfailure

.changelog/1034.txt, docs/resources/password_policy.md, examples/resources/pingone_password_policy/resource.tf, go.work.sum, internal/service/sso/resource_password_policy.go, internal/service/sso/resource_password_policy_test.go
Remove default values for fields in `min_characters` object in `pingone_password_policy` resource
```shell
TF_ACC=1 go test -v -timeout 240s -run ^TestAccPasswordPolicy -count=1 ./internal/service/sso 
```
<details>
```shell
=== RUN   TestAccPasswordPolicyDataSource_ByNameFull
=== PAUSE TestAccPasswordPolicyDataSource_ByNameFull
=== RUN   TestAccPasswordPolicyDataSource_ByIDFull
=== PAUSE TestAccPasswordPolicyDataSource_ByIDFull
=== RUN   TestAccPasswordPolicyDataSource_NotFound
=== PAUSE TestAccPasswordPolicyDataSource_NotFound
=== RUN   TestAccPasswordPolicy_RemovalDrift
=== PAUSE TestAccPasswordPolicy_RemovalDrift
=== RUN   TestAccPasswordPolicy_NewEnv
=== PAUSE TestAccPasswordPolicy_NewEnv
=== RUN   TestAccPasswordPolicy_Full
=== PAUSE …
```
=> Allow pingone_password_policy min_characters to be disabled

internal/service/base/resource_notification_settings_email_test.go
Update test coverage for `resource/pingone_notification_settings_email`
```shell
TF_ACC=1 go test -v -timeout 3000s -run ^TestAccNotificationSettingsEmail_CustomProvider_POST_RawBody github.com/pingidentity/terraform-provider-pingone/internal/service/base
```
<details>
```shell
=== RUN   TestAccNotificationSettingsEmail_CustomProvider_POST_RawBody
=== PAUSE TestAccNotificationSettingsEmail_CustomProvider_POST_RawBody
=== CONT  TestAccNotificationSettingsEmail_CustomProvider_POST_RawBody
--- PASS: TestAccNotificationSettingsEmail_CustomProvider_POST_RawBody (50.11s)
PASS
ok  	github.com/pingidentity/terraform-provider-pingone/internal/service/base	50.638s
```
</details>
=> `resource/pingone_notification_settings_email`: add test coverage for raw body

.github/workflows/acceptance-test-ff-multi-region.yml, .github/workflows/acceptance-test-multi-region.yml
Bump max Terraform version in tests.
Changelog not required.
N/a
- GA: https://github.com/pingidentity/terraform-provider-pingone/actions/runs/17617454837 (transient errors noted, not related to Terraform version)
- FF/Beta: https://github.com/pingidentity/terraform-provider-pingone/actions/runs/17617460819
=> Update latest terraform version in tests
